import { ArrowLeft, FileSearch, Microscope, ShieldAlert } from 'lucide-react'
import type { ReactNode } from 'react'
import { useForgeSight } from '../../context/useForgeSight'
import { navigate, type AppRoute } from '../../navigation'

const unavailable = 'Not available in supplied data.'
function DetailLayout({ eyebrow, title, icon: Icon, children }: { eyebrow: string; title: string; icon: typeof ShieldAlert; children: ReactNode }) {
  return <div className="analytical-page"><button className="back-link" type="button" onClick={() => navigate('quality-intelligence')}><ArrowLeft size={15} /> Back to quality intelligence</button><div className="module-heading"><div className="module-icon"><Icon size={21} /></div><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div></div>{children}</div>
}
function EvidenceList({ ids }: { ids: string[] }) { const { data } = useForgeSight(); return <div className="evidence-list">{ids.map((id) => { const item = data?.evidence.find((evidence) => evidence.evidenceId === id); return item ? <div className="evidence-item" key={item.evidenceId}><div><span className={`evidence-status ${item.status.toLowerCase()}`}>{item.status}</span><strong>{item.type}</strong><p>{item.statement}</p></div><code>{item.evidenceId}</code></div> : null })}</div> }

export function QualityDetailPage({ route }: { route: AppRoute }) {
  const { data } = useForgeSight()
  if (!data) return <DetailLayout eyebrow="Quality" title="No detail available" icon={ShieldAlert}><p className="page-description">Load the shared demo dataset before opening detail views.</p></DetailLayout>
  if (route.path === 'defect-detail') return <DefectDetail defectType={route.selectedId ?? data.defects[0]?.defectType ?? 'Unknown'} />
  if (route.path === 'unit-detail') return <UnitDetail unitId={route.selectedId ?? data.units[0]?.unitId ?? ''} />
  if (route.path === 'uncertainty-detail') return <UncertaintyDetail unitId={route.selectedId ?? ''} />
  return <NovelPatternDetail unitId={route.selectedId ?? ''} />
}

function UnitDetail({ unitId }: { unitId: string }) { const { data } = useForgeSight(); const unit = data?.units.find((item) => item.unitId === unitId); if (!unit) return <DetailLayout eyebrow="Unit detail" title="Unit not found" icon={FileSearch}><p className="page-description">The selected unit is not present in the supplied data.</p></DetailLayout>; return <DetailLayout eyebrow="Unit detail / Observed record" title={unit.unitId} icon={FileSearch}><div className="detail-grid"><DetailField label="Batch" value={unit.batchId} /><DetailField label="Line" value={unit.line} /><DetailField label="Classification" value={unit.classification === 'NOVEL' ? 'POTENTIAL NOVEL' : unit.classification} /><DetailField label="Defect" value={unit.defectType ?? 'Not available in supplied data.'} /><DetailField label="Process stage" value={unit.processStage} /><DetailField label="Timestamp" value={new Date(unit.timestamp).toLocaleString()} /><DetailField label="Confidence" value="Not available in supplied data." /><DetailField label="Location" value="Not available in supplied data." /><DetailField label="Status" value={unit.status} /></div></DetailLayout> }
function UncertaintyDetail({ unitId }: { unitId: string }) { const { data, setActiveInvestigation } = useForgeSight(); const unit = data?.units.find((item) => item.unitId === unitId && item.classification === 'UNCERTAIN'); const investigation = data?.investigations[0]; return <DetailLayout eyebrow="Uncertainty detail / Review required" title="Uncertain observation" icon={ShieldAlert}><div className="detail-callout warning"><strong>No known defect category meets the current confidence threshold.</strong><p>The supplied record remains UNCERTAIN. ForgeSight does not force the observation into a known class.</p></div>{unit && <div className="detail-grid"><DetailField label="Affected unit" value={unit.unitId} /><DetailField label="Batch" value={unit.batchId} /><DetailField label="Line" value={unit.line} /><DetailField label="Available evidence" value="Unit record and inspection classification" /><DetailField label="Confidence" value="Not available in supplied data." /><DetailField label="Closest known categories" value="Not available in supplied data." /><DetailField label="Reason classification was withheld" value="No known defect category meets the current confidence threshold." /><DetailField label="Recommended review" value="Engineering review of the inspection record and adjacent process observations." /></div>}<EvidenceList ids={data?.evidence.filter((item) => item.sourceIds.includes(unit?.unitId ?? '')).map((item) => item.evidenceId) ?? []} /><div className="detail-actions"><button className="secondary-button" type="button" onClick={() => navigate('data-evidence')}><FileSearch size={15} /> View evidence</button><button className="primary-button" type="button" onClick={() => { if (investigation) setActiveInvestigation(investigation.investigationId); navigate('investigation-center') }}><Microscope size={15} /> Open investigation</button></div></DetailLayout> }
function NovelPatternDetail({ unitId }: { unitId: string }) { const { data, setActiveInvestigation } = useForgeSight(); const unit = data?.units.find((item) => item.unitId === unitId && item.classification === 'NOVEL'); const investigation = data?.investigations[0]; return <DetailLayout eyebrow="Potential novel pattern / Engineering review required" title="POTENTIAL NOVEL PATTERN" icon={ShieldAlert}><div className="detail-callout novel"><strong>ENGINEERING REVIEW REQUIRED</strong><p>This observation is not a confirmed new defect. The supplied data does not support a known classification.</p></div>{unit && <div className="detail-grid"><DetailField label="Observation count" value="1 supplied observation" /><DetailField label="Affected batch" value={unit.batchId} /><DetailField label="Affected line" value={unit.line} /><DetailField label="First occurrence" value={new Date(unit.timestamp).toLocaleString()} /><DetailField label="Temporal pattern" value="Not available in supplied data." /><DetailField label="Characteristics" value="Not available in supplied data." /><DetailField label="Similarity to known patterns" value="Not available in supplied data." /><DetailField label="Supporting evidence" value="Unit record only" /><DetailField label="Engineering review recommendation" value="Review inspection evidence and compare against approved defect definitions." /></div>}<div className="detail-actions"><button className="primary-button" type="button" onClick={() => { if (investigation) setActiveInvestigation(investigation.investigationId); navigate('investigation-center') }}><Microscope size={15} /> Open investigation</button></div></DetailLayout> }
function DefectDetail({ defectType }: { defectType: string }) { const { data, setActiveInvestigation } = useForgeSight(); const defect = data?.defects.find((item) => item.defectType === defectType) ?? data?.defects[0]; const investigation = data?.investigations.find((item) => item.defectType === defect?.defectType); const relatedEvidence = data?.evidence.filter((item) => item.sourceIds.includes(defect?.defectId ?? '') || item.statement.includes(defect?.defectType ?? '')) ?? []; if (!defect) return <DetailLayout eyebrow="Defect detail" title="Defect not found" icon={ShieldAlert}><p className="page-description">The selected defect is not present in the supplied data.</p></DetailLayout>; return <DetailLayout eyebrow="Defect detail / Observed association" title={defect.defectType} icon={ShieldAlert}><div className="quality-stat-grid"><div className="quality-stat critical"><span>Occurrence count</span><strong>{defect.occurrenceCount}</strong><small>observed</small></div><div className="quality-stat"><span>Affected units</span><strong>{defect.affectedUnits.length}</strong><small>observed</small></div><div className="quality-stat"><span>Affected batches</span><strong>{defect.affectedBatches.join(', ')}</strong><small>observed</small></div><div className="quality-stat"><span>Affected lines</span><strong>{defect.affectedLines.join(', ')}</strong><small>observed</small></div></div><div className="detail-grid"><DetailField label="Trend" value="Observed recurrence in supplied batches." /><DetailField label="Process associations" value="Cooling is the affected process stage in B-2048; this is an observed association." /><DetailField label="Economic impact" value={data?.economics ? `Estimated revenue exposure: ${data.economics.revenueExposure.toLocaleString()} demo currency units.` : unavailable} /><DetailField label="Related investigation" value={investigation ? investigation.investigationId : unavailable} /></div><EvidenceList ids={relatedEvidence.map((item) => item.evidenceId)} /><div className="detail-actions">{investigation && <button className="primary-button" type="button" onClick={() => { setActiveInvestigation(investigation.investigationId); navigate('investigation-center') }}><Microscope size={15} /> View investigation</button>}</div></DetailLayout> }
function DetailField({ label, value }: { label: string; value: string }) { return <div className="detail-field"><span>{label}</span><strong>{value}</strong></div> }
