import { ArrowRight, ClipboardCheck, FileSearch, Search, ShieldAlert } from 'lucide-react'
import { useState } from 'react'
import { useForgeSight } from '../context/useForgeSight'
import type { DemoDataset, EvidenceItem, EvidenceStatus } from '../data/types'
import { navigate, type AppRoute, type PagePath } from '../navigation'

const evidenceOrder: EvidenceItem['type'][] = ['DEFECT INCREASE', 'PROCESS DEVIATION', 'POTENTIAL CONTRIBUTOR', 'BOTTLENECK', 'THROUGHPUT IMPACT', 'ECONOMIC IMPACT', 'RECOMMENDATION']
const statusFilters: Array<'ALL' | EvidenceStatus> = ['ALL', 'OBSERVED', 'ESTIMATED', 'SIMULATED', 'HYPOTHESIS']

export function DataEvidencePage({ route }: { route: AppRoute }) {
  void route
  const { data, isDemoLoaded, loadDemoData } = useForgeSight()
  if (!isDemoLoaded || !data) return <DataEvidenceEmptyState loadDemoData={loadDemoData} />
  return <DataEvidenceWorkspace data={data} />
}

function DataEvidenceWorkspace({ data }: { data: DemoDataset }) {
  const [activeFilter, setActiveFilter] = useState<'ALL' | EvidenceStatus>('ALL')
  const [search, setSearch] = useState('')
  const [selectedEvidenceId, setSelectedEvidenceId] = useState(data.evidence[0]?.evidenceId ?? null)
  const investigation = data.investigations[0]
  const chain = evidenceOrder.map((type) => data.evidence.find((item) => item.type === type)).filter((item): item is EvidenceItem => Boolean(item))
  const selectedEvidence = data.evidence.find((item) => item.evidenceId === selectedEvidenceId) ?? chain[0]
  const query = search.trim().toLowerCase()
  const filteredEvidence = data.evidence.filter((item) => {
    const matchesStatus = activeFilter === 'ALL' || item.status === activeFilter
    const searchable = [item.type, item.status, item.statement, item.evidenceId, ...item.sourceIds, ...item.linkedEvidenceIds].join(' ').toLowerCase()
    return matchesStatus && (!query || searchable.includes(query))
  })
  const sourceIds = selectedEvidence?.sourceIds ?? []

  return <div className="evidence-page">
    <header className="evidence-header"><div className="evidence-heading-icon"><ClipboardCheck size={22} /></div><div><span className="eyebrow">EVIDENCE</span><h1>Data &amp; Evidence</h1><p>Trace every decision from observed data to derived impact and advisory recommendations.</p></div><span className="demo-badge">DEMO MODE</span></header>
    <div className="evidence-context"><span>{investigation?.investigationId ?? 'CASE NOT AVAILABLE'}</span><span>{investigation?.batchId ?? 'BATCH NOT AVAILABLE'}</span><span>{investigation?.line ?? 'LINE NOT AVAILABLE'}</span><span>{data.productionStages.find((item) => item.stage === 'COOLING')?.stage ?? 'STAGE NOT AVAILABLE'}</span><span>{investigation?.defectType ?? 'DEFECT NOT AVAILABLE'}</span></div>
    <div className="evidence-banner"><ShieldAlert size={15} /><strong>EVIDENCE TRACEABILITY - ADVISORY ONLY</strong><span>Evidence preserves supplied facts, calculations, simulations, and hypotheses without confirming causality.</span></div>

    <section className="evidence-panel"><PanelHeading eyebrow="Section 01 / Dataset overview" title="Loaded dataset" description="Coverage is calculated directly from the shared ForgeSight demo dataset." /><div className="evidence-overview-grid"><OverviewItem label="Dataset ID" value={data.datasetId} /><OverviewItem label="Dataset label" value={data.label} /><OverviewItem label="Units" value={data.units.length} /><OverviewItem label="Batches" value={data.batches.length} /><OverviewItem label="Defects" value={data.defects.length} /><OverviewItem label="Process observations" value={data.processObservations.length} /><OverviewItem label="Production stages" value={data.productionStages.length} /><OverviewItem label="Economics" value={data.economics ? 'AVAILABLE' : 'NOT AVAILABLE'} status={data.economics ? 'OBSERVED' : undefined} /><OverviewItem label="Recommendations" value={data.recommendations.length} /><OverviewItem label="Evidence records" value={data.evidence.length} /></div></section>

    <section className="evidence-panel"><PanelHeading eyebrow="Section 02 / Evidence chain" title="From signal to recommendation" description="Select a node to inspect its record, provenance, linked evidence, and next action." /><div className="evidence-chain-workspace">{chain.length ? <><EvidenceGroup label="OBSERVED / DERIVED EVIDENCE" items={chain.filter((item) => item.status !== 'HYPOTHESIS')} selectedEvidenceId={selectedEvidence?.evidenceId} onSelect={setSelectedEvidenceId} /><EvidenceGroup label="HYPOTHESIS / ADVISORY INTERPRETATION" items={chain.filter((item) => item.status === 'HYPOTHESIS')} selectedEvidenceId={selectedEvidence?.evidenceId} onSelect={setSelectedEvidenceId} /></> : <EmptyEvidenceState />}</div>{selectedEvidence && <EvidenceDetail item={selectedEvidence} data={data} onSelectEvidence={setSelectedEvidenceId} />}</section>

    <section className="evidence-panel"><div className="evidence-table-heading"><PanelHeading eyebrow="Section 03 / Evidence table" title="Searchable evidence register" description="Search statements and identifiers, then filter by the exact supplied status value." /><label className="evidence-search"><Search size={15} /><span className="sr-only">Search evidence</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search evidence" /></label></div><div className="evidence-filter-row">{statusFilters.map((filter) => <button key={filter} type="button" className={`evidence-filter ${activeFilter === filter ? 'is-selected' : ''}`} onClick={() => setActiveFilter(filter)}>{filter}</button>)}</div>{filteredEvidence.length ? <div className="evidence-table-wrap"><table><thead><tr><th>Type</th><th>Status</th><th>Statement</th><th>Evidence ID</th><th>Sources</th><th>Linked evidence</th></tr></thead><tbody>{filteredEvidence.map((item) => <tr key={item.evidenceId} className={selectedEvidence?.evidenceId === item.evidenceId ? 'selected-row' : ''} onClick={() => setSelectedEvidenceId(item.evidenceId)}><td>{item.type}</td><td><StatusBadge status={item.status} /></td><td className="evidence-statement-cell">{item.statement}</td><td><code>{item.evidenceId}</code></td><td><IdentifierList values={item.sourceIds} /></td><td><IdentifierList values={item.linkedEvidenceIds} emptyLabel="-" /></td></tr>)}</tbody></table></div> : <EmptyEvidenceState search={search} />}</section>

    <section className="evidence-two-column"><section className="evidence-panel"><PanelHeading eyebrow="Section 04 / Source traceability" title="Supporting records" description={selectedEvidence ? `Identifiers supporting ${selectedEvidence.evidenceId}.` : 'Identifiers supporting the current case.'} /><TraceabilityGroups data={data} sourceIds={sourceIds} /></section><section className="evidence-panel"><PanelHeading eyebrow="Section 05 / Data honesty" title="Interpretation rules" description="ForgeSight keeps evidence status visible at every step." /><div className="honesty-list"><HonestyItem status="OBSERVED" text="Directly represented in supplied data." /><HonestyItem status="ESTIMATED" text="Calculated from supplied assumptions." /><HonestyItem status="SIMULATED" text="Scenario output, not an observed result." /><HonestyItem status="HYPOTHESIS" text="A contributor requiring verification; not confirmed." /></div></section></section>

    <footer className="evidence-actions"><ActionButton label="Open Quality Intelligence" path="quality-intelligence" /><ActionButton label="Open Investigation" path="investigation-center" /><ActionButton label="Open Economic Impact" path="economic-impact" /><ActionButton label="Open Decision Center" path="decision-center" /></footer>
  </div>
}

function PanelHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="evidence-panel-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div> }
function OverviewItem({ label, value, status }: { label: string; value: string | number; status?: EvidenceStatus }) { return <div className="evidence-overview-item"><span className="label">{label}</span><strong>{value}</strong>{status && <StatusBadge status={status} />}</div> }
function StatusBadge({ status }: { status: EvidenceStatus }) { return <span className={`status-badge status-${status.toLowerCase()}`}>{status}</span> }
function IdentifierList({ values, emptyLabel }: { values: string[]; emptyLabel?: string }) { return <span className="identifier-list">{values.length ? values.map((value) => <code key={value}>{value}</code>) : emptyLabel}</span> }
function EvidenceGroup({ label, items, selectedEvidenceId, onSelect }: { label: string; items: EvidenceItem[]; selectedEvidenceId?: string; onSelect: (evidenceId: string) => void }) { return <div className={`evidence-group ${label.startsWith('HYPOTHESIS') ? 'is-hypothesis' : ''}`}><div className="evidence-group-heading"><span>{label}</span><small>{items.length} record{items.length === 1 ? '' : 's'}</small></div><div className="evidence-group-nodes">{items.length ? items.map((item, index) => <EvidenceChainCard key={item.evidenceId} item={item} index={index} selected={item.evidenceId === selectedEvidenceId} onSelect={() => onSelect(item.evidenceId)} />) : <span className="evidence-group-empty">Not available in supplied data.</span>}</div></div> }
function EvidenceChainCard({ item, index, selected, onSelect }: { item: EvidenceItem; index: number; selected: boolean; onSelect: () => void }) { return <button type="button" className={`evidence-chain-card ${selected ? 'is-selected' : ''}`} onClick={onSelect}><span className="chain-number">{String(index + 1).padStart(2, '0')}</span><strong>{item.type}</strong><StatusBadge status={item.status} /><p>{item.statement}</p><span className="chain-meta"><code>{item.evidenceId}</code><small>{item.sourceIds.length} source{item.sourceIds.length === 1 ? '' : 's'} / {item.linkedEvidenceIds.length} linked</small></span></button> }
function EvidenceDetail({ item, data, onSelectEvidence }: { item: EvidenceItem; data: DemoDataset; onSelectEvidence: (evidenceId: string) => void }) {
  const recommendation = data.recommendations.find((candidate) => candidate.evidence.includes(item.evidenceId))
  const sourceIds = item.sourceIds
  const traceableIds = traceableIdsFor(data, sourceIds)
  const interpretation = item.status === 'OBSERVED' ? 'Directly represented in supplied data.' : item.status === 'ESTIMATED' ? 'Calculated from supplied inputs.' : item.status === 'SIMULATED' ? 'Scenario output, not an observed result.' : 'Possible contributor requiring verification; not confirmed.'
  return <div className={`evidence-detail ${item.status === 'HYPOTHESIS' ? 'is-hypothesis' : ''}`}><div className="evidence-detail-heading"><div><span className="eyebrow">Selected evidence</span><h3>{item.type}</h3><code>{item.evidenceId}</code></div><StatusBadge status={item.status} /></div><div className="evidence-detail-grid"><div className="evidence-detail-block"><span className="label">Statement</span><p className="evidence-detail-statement">{item.statement}</p></div><div className="evidence-detail-block"><span className="label">Evidence interpretation</span><p>{interpretation}</p></div><div className="evidence-detail-block"><span className="label">Source records</span><IdentifierList values={item.sourceIds} emptyLabel="Not available in supplied data." /></div><div className="evidence-detail-block"><span className="label">Linked evidence</span><div className="linked-evidence-list">{item.linkedEvidenceIds.length ? item.linkedEvidenceIds.map((evidenceId) => <button key={evidenceId} type="button" onClick={() => onSelectEvidence(evidenceId)}>{evidenceId}<ArrowRight size={12} /></button>) : <span>Not available in supplied data.</span>}</div></div><div className="evidence-detail-block"><span className="label">Investigation next step</span><p>{recommendation?.recommendedInvestigation ?? 'Further investigation required.'}</p></div><div className="evidence-detail-block"><span className="label">Traceability</span><TraceabilitySummary data={data} sourceIds={traceableIds} /></div></div></div>
}
function traceableIdsFor(data: DemoDataset, sourceIds: string[]) { return sourceIds.filter((sourceId) => data.units.some((item) => item.unitId === sourceId) || data.batches.some((item) => item.batchId === sourceId) || data.defects.some((item) => item.defectId === sourceId) || data.processObservations.some((item) => item.observationId === sourceId) || data.productionStages.some((item) => item.stageId === sourceId) || data.economics.economicsId === sourceId || data.recommendations.some((item) => item.id === sourceId) || data.investigations.some((item) => item.investigationId === sourceId)) }
function TraceabilitySummary({ data, sourceIds }: { data: DemoDataset; sourceIds: string[] }) { const groups: Array<[string, string[]]> = [['Unit IDs', data.units.map((item) => item.unitId).filter((id) => sourceIds.includes(id))], ['Batch IDs', data.batches.map((item) => item.batchId).filter((id) => sourceIds.includes(id))], ['Defect IDs', data.defects.map((item) => item.defectId).filter((id) => sourceIds.includes(id))], ['Process observation IDs', data.processObservations.map((item) => item.observationId).filter((id) => sourceIds.includes(id))], ['Production stage IDs', data.productionStages.map((item) => item.stageId).filter((id) => sourceIds.includes(id))], ['Economics ID', sourceIds.includes(data.economics.economicsId) ? [data.economics.economicsId] : []], ['Recommendation ID', data.recommendations.flatMap((item) => sourceIds.includes(item.id) ? [item.id] : [])]]; const available = groups.filter(([, values]) => values.length); return available.length ? <div className="traceability-summary">{available.map(([label, values]) => <div key={label}><span>{label}</span><IdentifierList values={values} /></div>)}</div> : <span>Not available in supplied data.</span> }
function TraceabilityGroups({ data, sourceIds }: { data: DemoDataset; sourceIds: string[] }) { const groups: Array<[string, string[]]> = [['Unit IDs', data.units.map((item) => item.unitId).filter((id) => sourceIds.includes(id))], ['Batch IDs', data.batches.map((item) => item.batchId).filter((id) => sourceIds.includes(id))], ['Defect IDs', data.defects.map((item) => item.defectId).filter((id) => sourceIds.includes(id))], ['Process observation IDs', data.processObservations.map((item) => item.observationId).filter((id) => sourceIds.includes(id))], ['Production stage IDs', data.productionStages.map((item) => item.stageId).filter((id) => sourceIds.includes(id))], ['Economics ID', data.economics && sourceIds.includes(data.economics.economicsId) ? [data.economics.economicsId] : []], ['Recommendation ID', data.recommendations.flatMap((item) => sourceIds.includes(item.id) ? [item.id] : [])]]; return <div className="traceability-list">{groups.map(([label, values]) => <div key={label}><span className="label">{label}</span><IdentifierList values={values} emptyLabel="Not present in evidence sources." /></div>)}</div> }
function HonestyItem({ status, text }: { status: EvidenceStatus; text: string }) { return <div><StatusBadge status={status} /><p>{text}</p></div> }
function EmptyEvidenceState({ search }: { search?: string }) { return <div className="evidence-empty"><FileSearch size={18} /><strong>{search ? 'No matching evidence records' : 'No evidence records supplied'}</strong><p>{search ? 'Try a different search term or status filter.' : 'The shared dataset contains no evidence to trace.'}</p></div> }
function ActionButton({ label, path }: { label: string; path: PagePath }) { return <button className="secondary-button" type="button" onClick={() => navigate(path)}>{label}<ArrowRight size={14} /></button> }
function DataEvidenceEmptyState({ loadDemoData }: { loadDemoData: () => void }) { return <div className="page-view"><div className="page-heading"><div className="heading-icon"><ClipboardCheck size={21} /></div><div><span className="eyebrow">EVIDENCE</span><h1>Data &amp; Evidence</h1></div></div><p className="page-description">Load the centralized ForgeSight demo dataset to trace observed data, derived impact, and advisory recommendations.</p><button className="primary-button" type="button" onClick={loadDemoData}>Load demo data <ArrowRight size={15} /></button></div> }