import { ArrowRight, CircleDollarSign, FileSearch, GitBranch, ShieldAlert, SlidersHorizontal, Target } from 'lucide-react'
import { useForgeSight } from '../context/useForgeSight'
import { calculateEconomicImpact } from '../data/economicCalculations'
import type { EvidenceItem, EvidenceStatus } from '../data/types'
import { navigate, type AppRoute } from '../navigation'

const unavailable = 'Not available in supplied data.'
const evidenceOrder: EvidenceItem['type'][] = ['DEFECT INCREASE', 'PROCESS DEVIATION', 'POTENTIAL CONTRIBUTOR', 'BOTTLENECK', 'THROUGHPUT IMPACT', 'ECONOMIC IMPACT', 'RECOMMENDATION']

export function DecisionCenterPage({ route }: { route: AppRoute }) {
  const { data, isDemoLoaded, loadDemoData, activeInvestigationId, setActiveInvestigation } = useForgeSight()
  void route
  if (!isDemoLoaded || !data) return <DecisionEmptyState loadDemoData={loadDemoData} />

  const investigation = data.investigations.find((item) => item.investigationId === activeInvestigationId) ?? data.investigations[0]
  const batch = data.batches.find((item) => item.batchId === investigation?.batchId)
  const stage = data.productionStages.find((item) => item.stage === batch?.affectedProcessStage)
  const recommendation = data.recommendations.find((item) => item.id === 'REC-2048-01') ?? data.recommendations[0]
  const economic = calculateEconomicImpact(data.economics, batch, stage)
  const evidence = evidenceOrder.map((type) => data.evidence.find((item) => item.type === type)).filter((item): item is EvidenceItem => Boolean(item))
  const go = (path: Parameters<typeof navigate>[0]) => { if (investigation) setActiveInvestigation(investigation.investigationId); navigate(path) }

  return <div className="decision-page">
    <header className="decision-header"><div className="decision-heading-icon"><Target size={22} /></div><div><span className="eyebrow">Decision</span><h1>Decision Center</h1><p>Review the evidence chain, scenario results, and recommended next steps before taking an engineering action.</p></div><span className="demo-badge">DEMO MODE</span></header>
    <div className="decision-context"><span>{investigation?.investigationId ?? unavailable}</span><span>{batch?.batchId ?? unavailable}</span><span>{batch?.line ?? investigation?.line ?? unavailable}</span><span>{stage?.stage ?? unavailable}</span><span>{investigation?.defectType ?? unavailable}</span></div>
    <div className="decision-banner"><ShieldAlert size={17} /><strong>DECISION SUPPORT</strong><span>ADVISORY ONLY - ENGINEERING REVIEW REQUIRED</span></div>

    <section className="decision-panel"><PanelHeading eyebrow="Case context" title="Case summary" description="Observed context from the shared investigation dataset." /><div className="decision-summary-grid"><SummaryItem label="Batch" value={batch?.batchId ?? unavailable} status="OBSERVED" /><SummaryItem label="Line" value={batch?.line ?? investigation?.line ?? unavailable} status="OBSERVED" /><SummaryItem label="Defect" value={investigation?.defectType ?? unavailable} status="OBSERVED" /><SummaryItem label="Affected process stage" value={stage?.stage ?? unavailable} status="OBSERVED" /><SummaryItem label="Observed defect rate" value={batch ? `${(batch.defectRate * 100).toFixed(1)}%` : unavailable} status="OBSERVED" /><SummaryItem label="Observed cooling throughput" value={stage ? `${stage.throughput} units/hr` : unavailable} status="OBSERVED" /><SummaryItem label="Cooling capacity" value={stage ? `${stage.capacity} units/hr` : unavailable} status="OBSERVED" /><SummaryItem label="Cooling utilization" value={stage ? `${stage.utilization}%` : unavailable} status="OBSERVED" /></div></section>

    <section className="decision-panel"><PanelHeading eyebrow="Traceability" title="Evidence chain" description="Evidence status is preserved; a hypothesis is not confirmation." /><div className="decision-evidence-chain">{evidence.map((item, index) => <div className="decision-evidence-item" key={item.evidenceId}><div className="decision-evidence-step"><span>{String(index + 1).padStart(2, '0')}</span><strong>{item.type}</strong><StatusBadge status={item.status} /></div><p>{item.statement}</p><div className="decision-id-list"><span>Evidence: {item.evidenceId}</span><span>Sources: {item.sourceIds.join(', ') || unavailable}</span>{item.linkedEvidenceIds.length > 0 && <span>Linked: {item.linkedEvidenceIds.join(', ')}</span>}</div></div>)}</div></section>

    <div className="decision-two-column"><section className="decision-panel"><PanelHeading eyebrow="Current recommendation" title="Engineering review" description="Supplied recommendation record." />{recommendation ? <><div className="recommendation-header"><span className="status-badge status-uncertain">EVIDENCE STRENGTH: {recommendation.evidenceStrength}</span><span className="status-badge status-warning">{recommendation.status}</span></div><div className="decision-detail-list"><Detail label="Issue" value={recommendation.issue} /><Detail label="Potential contributor" value={`${recommendation.potentialContributor}. Cooling-stage deviation is a potential contributor; this dataset does not establish causality.`} /><Detail label="Affected area" value={recommendation.affectedArea} /><Detail label="Recommended investigation" value={recommendation.recommendedInvestigation} /></div></> : <p className="decision-muted">{unavailable}</p>}</section><section className="decision-panel"><PanelHeading eyebrow="Investigation" title="Investigation status" description="The underlying case remains in its supplied state." />{investigation ? <div className="investigation-card"><span className="status-badge status-warning">{investigation.status}</span><strong>{investigation.investigationId}</strong><h3>{investigation.title}</h3><div className="decision-detail-list"><Detail label="Batch" value={investigation.batchId} /><Detail label="Line" value={investigation.line} /><Detail label="Defect type" value={investigation.defectType} /></div></div> : <p className="decision-muted">{unavailable}</p>}</section></div>

    <section className="decision-panel"><PanelHeading eyebrow="Economics" title="Estimated exposure components" description="Separate estimated components from the shared data layer; no additive total is implied." />{economic.isPartial && <div className="decision-partial"><ShieldAlert size={15} /><strong>ECONOMIC DATA PARTIAL</strong><span>{economic.missingAssumptions.join('; ')}</span></div>}<div className="decision-economic-grid">{economic.rows.map((row) => <SummaryItem key={row.key} label={row.label} value={row.displayValue} status={row.status} />)}</div><button className="secondary-button decision-inline-action" type="button" onClick={() => go('economic-impact')}><CircleDollarSign size={15} /> Open Economic Impact</button></section>

    <section className="decision-panel"><PanelHeading eyebrow="Simulation context" title="Available profitability scenarios" description="Scenario records are advisory and are not observed production results." />{data.profitabilityScenarios.length > 0 ? <div className="decision-scenario-list">{data.profitabilityScenarios.map((scenario) => <article key={scenario.scenarioId} className="decision-scenario"><div><strong>{scenario.label}</strong><p>{scenario.assumption}</p></div><div className="decision-scenario-values"><span className={`status-badge ${scenario.status === 'BASELINE' ? 'status-observed' : 'status-simulated'}`}>{scenario.status}</span><span>Unit margin: {scenario.unitMargin}</span><span>Expected daily margin: {scenario.expectedDailyMargin.toLocaleString()}</span></div></article>)}</div> : <p className="decision-muted">{unavailable}</p>}<button className="secondary-button decision-inline-action" type="button" onClick={() => go('profitability-simulator')}><SlidersHorizontal size={15} /> Open Profitability Simulator</button></section>

    <section className="decision-panel"><PanelHeading eyebrow="Decision record" title="Current decision state" description="A review state, not an autonomous decision." /><div className="decision-state-grid"><StateItem label="Evidence status" value="Review required" /><StateItem label="Contributor status" value="HYPOTHESIS - NOT CONFIRMED" /><StateItem label="Economic status" value="ESTIMATED" /><StateItem label="Simulation status" value="SIMULATED / ADVISORY ONLY" /></div><div className="decision-action-note"><ShieldAlert size={16} /><span><b>Engineering action:</b> {recommendation?.recommendedInvestigation ?? 'Verify cooling-stage controls before treating the potential contributor as causal.'}</span></div></section>

    <section className="decision-panel"><PanelHeading eyebrow="Traceability" title="Investigation record" description="Identifiers connect the decision surface to supplied records." /><div className="decision-trace-list">{[['Case', investigation?.investigationId], ['Batch', batch?.batchId], ['Defect', data.defects.find((item) => item.defectType === investigation?.defectType)?.defectId], ['Process observations', data.processObservations.filter((item) => item.batchId === batch?.batchId).map((item) => item.observationId).join(', ')], ['Production stage', stage?.stageId], ['Economic calculation', data.economics.economicsId], ['Simulation', data.profitabilityScenarios.map((item) => item.scenarioId).join(', ')], ['Recommendation', recommendation?.id], ['Evidence', evidence.map((item) => item.evidenceId).join(', ') ]].map(([label, value]) => <div key={label}><span className="label">{label}</span><strong>{value ?? unavailable}</strong></div>)}</div></section>

    <section className="decision-panel decision-actions-panel"><PanelHeading eyebrow="Next steps" title="Available actions" description="Open an existing ForgeSight module for review." /><div className="decision-actions"><button className="secondary-button" type="button" onClick={() => go('data-evidence')}><FileSearch size={15} /> Review Evidence <ArrowRight size={14} /></button><button className="secondary-button" type="button" onClick={() => go('investigation-center')}><GitBranch size={15} /> Open Investigation <ArrowRight size={14} /></button><button className="secondary-button" type="button" onClick={() => go('economic-impact')}><CircleDollarSign size={15} /> Open Economic Impact <ArrowRight size={14} /></button><button className="primary-button" type="button" onClick={() => go('profitability-simulator')}><SlidersHorizontal size={15} /> Open Profitability Simulator <ArrowRight size={14} /></button></div></section>
  </div>
}

function PanelHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="decision-panel-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div> }
function SummaryItem({ label, value, status }: { label: string; value: string; status: string }) { return <div className="decision-summary-item"><span className="label">{label}</span><strong>{value}</strong><StatusBadge status={status as EvidenceStatus | 'PARTIAL'} /></div> }
function StatusBadge({ status }: { status: EvidenceStatus | 'PARTIAL' }) { const className = status === 'OBSERVED' ? 'status-observed' : status === 'ESTIMATED' ? 'status-estimated' : status === 'SIMULATED' ? 'status-simulated' : status === 'HYPOTHESIS' ? 'status-hypothesis' : 'status-warning'; return <span className={`status-badge ${className}`}>{status}</span> }
function Detail({ label, value }: { label: string; value: string }) { return <div><span className="label">{label}</span><p>{value}</p></div> }
function StateItem({ label, value }: { label: string; value: string }) { return <div><span className="label">{label}</span><strong>{value}</strong></div> }
function DecisionEmptyState({ loadDemoData }: { loadDemoData: () => void }) { return <div className="page-view"><div className="page-heading"><div className="heading-icon"><Target size={21} /></div><div><span className="eyebrow">Decision</span><h1>Decision Center</h1></div></div><p className="page-description">Load the centralized ForgeSight demo dataset to review evidence and recommended next steps.</p><button className="primary-button" type="button" onClick={loadDemoData}>Load demo data <ArrowRight size={15} /></button></div> }
