import { ArrowRight, Calculator, ChevronRight, CircleDollarSign, ExternalLink, FileSearch, Network, ShieldAlert, SlidersHorizontal } from 'lucide-react'
import { Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useForgeSight } from '../context/useForgeSight'
import { calculateEconomicImpact, type EconomicRow } from '../data/economicCalculations'
import { navigate, type AppRoute } from '../navigation'

const unavailable = 'Not available in supplied data.'
const chartColors = ['#d69a4c', '#e16b61', '#63b8d2', '#7eb8e6', '#78c99c']

export function EconomicImpactPage({ route }: { route: AppRoute }) {
  void route
  const { data, isDemoLoaded, loadDemoData, activeInvestigationId, setActiveInvestigation } = useForgeSight()
  if (!isDemoLoaded || !data) return <EconomicEmptyState loadDemoData={loadDemoData} />

  const investigation = data.investigations.find((item) => item.investigationId === activeInvestigationId) ?? data.investigations[0]
  const batch = data.batches.find((item) => item.batchId === investigation?.batchId)
  const stage = data.productionStages.find((item) => item.stage === batch?.affectedProcessStage)
  const economic = calculateEconomicImpact(data.economics, batch, stage)
  const evidence = data.evidence.find((item) => item.evidenceId === 'EVD-ECONOMIC-2048')
  const chartData = economic.rows.map((row) => ({ name: row.label.replace(' Cost', ''), amount: row.amount ?? 0 }))
  const go = (path: Parameters<typeof navigate>[0]) => { if (investigation) setActiveInvestigation(investigation.investigationId); navigate(path) }

  return <div className="economic-page">
    <header className="economic-header">
      <div className="economic-heading-icon"><CircleDollarSign size={22} /></div>
      <div className="economic-heading-copy"><span className="eyebrow">Economics / Investigation impact</span><h1>Economic Impact</h1><p>What does the operational problem cost?</p></div>
      <span className="demo-badge">DEMO MODE</span>
    </header>
    <div className="economic-context"><span>CASE {investigation?.investigationId ?? unavailable}</span><span>{batch?.batchId ?? unavailable}</span><span>{investigation?.line ?? unavailable}</span><span>{stage?.stage ?? investigation?.defectType ?? unavailable}</span><span className="status-badge status-estimated">ESTIMATED</span></div>
    <div className="economic-disclaimer"><ShieldAlert size={15} /><strong>ESTIMATED</strong><span>Based on supplied demo assumptions. This view communicates economic exposure, not confirmed causality.</span></div>

    <section className="economic-section"><SectionHeading eyebrow="Summary" title="Estimated exposure components" description="Five individually estimated components are shown without an additive total because overlap is not established by the supplied assumptions." /><div className="economic-component-notice"><ShieldAlert size={15} /><span>Components are not presented as a summed total.</span></div><div className="economic-metric-grid">{economic.rows.map((row) => <EconomicMetric key={row.key} row={row} />)}</div></section>

    <section className="economic-grid-layout"><section className="economic-panel economic-chart-panel"><SectionHeading eyebrow="Components" title="Estimated exposure by category" description="Individual estimated amounts; no share of a total is implied." /><div className="economic-chart"><ResponsiveContainer width="100%" height={290}><BarChart data={chartData} layout="vertical" margin={{ top: 4, right: 24, bottom: 4, left: 8 }}><XAxis type="number" hide /><YAxis type="category" dataKey="name" width={112} tick={{ fill: '#a9b8b6', fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: 'rgba(99,184,210,.07)' }} content={<ImpactTooltip />} /><Bar dataKey="amount" radius={[0, 2, 2, 0]}>{chartData.map((entry, index) => <Cell key={entry.name} fill={chartColors[index]} />)}</Bar></BarChart></ResponsiveContainer></div></section><ThroughputPanel stage={stage} /></section>

    <section className="economic-panel economic-method-panel"><div className="economic-panel-heading"><SectionHeading eyebrow="Traceability" title="Calculation methodology" description="Every displayed estimate is derived from the shared demo data." /><button className="calculation-button" type="button" onClick={() => document.getElementById('economic-method-details')?.toggleAttribute('hidden')}><Calculator size={15} /> How calculated? <ChevronRight size={14} /></button></div><div id="economic-method-details" className="economic-method-details" hidden><Methodology economic={economic} data={data} /></div></section>

    <EvidenceSection evidenceStatement={evidence?.statement} onView={() => document.getElementById('economic-evidence-chain')?.toggleAttribute('hidden')} /><div id="economic-evidence-chain" hidden><EvidenceChain /></div>

    <section className="economic-panel economic-table-panel"><SectionHeading eyebrow="Audit table" title="Estimated exposure components" description="Select a component to inspect its calculation basis." /><EconomicTable rows={economic.rows} /></section>

    <footer className="economic-actions"><button className="secondary-button" type="button" onClick={() => go('bottleneck-analysis')}><Network size={15} /> View bottleneck</button><button className="secondary-button" type="button" onClick={() => go('investigation-center')}><FileSearch size={15} /> View investigation</button><button className="primary-button" type="button" onClick={() => go('profitability-simulator')}><SlidersHorizontal size={15} /> Simulate scenario</button><button className="ghost-button" type="button" onClick={() => go('investigation-center')}><ExternalLink size={15} /> View evidence</button></footer>
  </div>
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="economic-section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div> }
function EconomicMetric({ row }: { row: EconomicRow }) { return <article className={`economic-metric ${row.status === 'PARTIAL' ? 'is-partial' : ''}`}><span className="label">{row.label}</span><strong>{row.displayValue}</strong><span className={`status-badge ${row.status === 'PARTIAL' ? 'status-warning' : 'status-estimated'}`}>{row.status}</span></article> }
function ImpactTooltip({ active, payload }: { active?: boolean; payload?: Array<{ payload: { name: string; amount: number } }> }) { if (!active || !payload?.[0]) return null; const item = payload[0].payload; return <div className="economic-tooltip"><strong>{item.name}</strong><span>{item.amount.toLocaleString()} demo currency units</span><small>ESTIMATED COMPONENT</small></div> }
function ThroughputPanel({ stage }: { stage?: { stage: string; capacity: number; throughput: number; utilization: number; queueWip: number } }) { const metrics = stage ? [['Cooling capacity', `${stage.capacity} units/hr`], ['Actual throughput', `${stage.throughput} units/hr`], ['Capacity gap', `${stage.capacity - stage.throughput} units/hr`], ['Queue / WIP', String(stage.queueWip)], ['Utilization', `${stage.utilization}%`]] : [['Cooling capacity', unavailable], ['Actual throughput', unavailable], ['Capacity gap', unavailable], ['Queue / WIP', unavailable], ['Utilization', unavailable]]; return <section className="economic-panel throughput-panel"><SectionHeading eyebrow="Production exposure" title="Throughput exposure" description="Observed cooling-stage operating context." /><div className="throughput-metrics">{metrics.map(([label, value]) => <div key={label}><span className="label">{label}</span><strong>{value}</strong><span className="status-badge status-observed">OBSERVED</span></div>)}</div><p className="engineering-note">Throughput exposure is an observed difference between supplied stage capacity and actual throughput; it is not a claim of causality.</p></section> }
function Methodology({ economic, data }: { economic: ReturnType<typeof calculateEconomicImpact>; data: NonNullable<ReturnType<typeof useForgeSight>['data']> }) { const batch = data.batches.find((item) => item.batchId === 'B-2048'); const stage = data.productionStages.find((item) => item.stage === 'COOLING'); return <div className="methodology-list">{economic.rows.map((row) => <div key={row.key} className="methodology-row"><span className="status-badge status-observed">OBSERVED INPUT</span><div><strong>{row.label}</strong><code>{row.formula}</code><small><b>ASSUMPTION</b> {row.key === 'throughput' ? `Unit margin derived from selling price ${data.economics.sellingPrice} - unit cost ${data.economics.unitCost}.` : row.key === 'downtime' || row.key === 'revenue' ? 'Supplied economic assumption.' : `Supplied ${row.key === 'scrap' || row.key === 'material' ? `B-2048 defect count ${batch?.defectCount ?? unavailable}` : `COOLING stage values ${stage?.capacity ?? unavailable} / ${stage?.throughput ?? unavailable}`}.`} <b>ESTIMATED OUTPUT</b> {row.displayValue}</small></div></div>)}</div> }
function EvidenceSection({ evidenceStatement, onView }: { evidenceStatement?: string; onView: () => void }) { return <section className="economic-panel evidence-link-panel"><div><span className="eyebrow">Evidence link</span><h2>Continue the engineering investigation</h2><p>{evidenceStatement ?? 'Economic evidence is not available in supplied data.'}</p></div><button className="secondary-button" type="button" onClick={onView}><FileSearch size={15} /> View evidence</button></section> }
function EvidenceChain() { return <section className="economic-evidence-chain"><div className="evidence-chain-step"><span>01</span><strong>QUALITY ANOMALY</strong><small>Observed</small></div><ArrowRight /><div className="evidence-chain-step"><span>02</span><strong>AFFECTED BATCH</strong><small>Observed</small></div><ArrowRight /><div className="evidence-chain-step"><span>03</span><strong>COOLING PROCESS OBSERVATION</strong><small>Observed</small></div><ArrowRight /><div className="evidence-chain-step"><span>04</span><strong>BOTTLENECK</strong><small>Potential contributor</small></div><ArrowRight /><div className="evidence-chain-step"><span>05</span><strong>THROUGHPUT EXPOSURE</strong><small>Observed</small></div><ArrowRight /><div className="evidence-chain-step"><span>06</span><strong>ECONOMIC ESTIMATE</strong><small>Estimated</small></div></section> }
function EconomicTable({ rows }: { rows: EconomicRow[] }) { return <div className="economic-table-wrap"><table><thead><tr><th>Component</th><th>Value</th><th>Status</th><th>Calculation basis</th></tr></thead><tbody>{rows.map((row) => <EconomicTableRow key={row.key} row={row} />)}</tbody></table><p className="engineering-note">These estimates are retained as separate exposure components; additive overlap is not established in the supplied assumptions.</p></div> }
function EconomicTableRow({ row }: { row: EconomicRow }) { return <details className="economic-table-row"><summary><span>{row.label}</span><span>{row.displayValue}</span><span><span className={`status-badge ${row.status === 'PARTIAL' ? 'status-warning' : 'status-estimated'}`}>{row.status}</span></span><span>{row.basis}</span></summary><div><strong>Calculation detail</strong><code>{row.formula}</code><p><b>ESTIMATED</b> / Derived from supplied shared data and assumptions. No causal claim is made.</p></div></details> }
function EconomicEmptyState({ loadDemoData }: { loadDemoData: () => void }) { return <div className="page-view"><div className="page-heading"><div className="heading-icon"><CircleDollarSign size={21} /></div><div><span className="eyebrow">Economics / Investigation impact</span><h1>Economic Impact</h1></div></div><p className="page-description">Load the centralized ForgeSight demo dataset to quantify the FS-2048 operational exposure.</p><button className="primary-button" type="button" onClick={loadDemoData}>Load demo data <ArrowRight size={15} /></button></div> }
