import { useEffect, useState, type ReactNode } from 'react'
import { ArrowDown, ArrowRight, BarChart3, Calculator, ChevronDown, ChevronRight, CircleDollarSign, ExternalLink, FileSearch, FlaskConical, Gauge, Microscope, Network, ShieldAlert, Target } from 'lucide-react'
import { useForgeSight } from '../context/useForgeSight'
import type { EvidenceItem, EvidenceStatus, ProcessObservation } from '../data/types'
import { calculateEconomicImpact } from '../data/economicCalculations'
import { navigate, type AppRoute } from '../navigation'

const unavailable = 'Not available in supplied data.'
const evidenceOrder = ['EVD-DEFECT-2048', 'EVD-DEVIATION-2048', 'EVD-TEMPORAL-2048', 'EVD-BATCH-2048', 'EVD-CONTRIBUTOR-2048', 'EVD-BOTTLENECK-2048', 'EVD-THROUGHPUT-2048', 'EVD-ECONOMIC-2048', 'EVD-RECOMMENDATION-2048']
const evidenceActions: Record<string, { label: string; path: Parameters<typeof navigate>[0]; id?: string }> = {
  'EVD-DEFECT-2048': { label: 'View defect', path: 'defect-detail', id: 'Surface Crack' },
  'EVD-DEVIATION-2048': { label: 'View process data', path: 'process-intelligence' },
  'EVD-TEMPORAL-2048': { label: 'View records', path: 'quality-intelligence' },
  'EVD-BATCH-2048': { label: 'View batch', path: 'data-evidence' },
  'EVD-CONTRIBUTOR-2048': { label: 'View process data', path: 'process-intelligence' },
  'EVD-BOTTLENECK-2048': { label: 'View bottleneck', path: 'bottleneck-analysis' },
  'EVD-THROUGHPUT-2048': { label: 'View process data', path: 'process-intelligence' },
  'EVD-ECONOMIC-2048': { label: 'View economic impact', path: 'economic-impact' },
  'EVD-RECOMMENDATION-2048': { label: 'Open decision', path: 'decision-center' },
}

export function InvestigationCenterPage({ route: _route }: { route: AppRoute }) {
  const { data, isDemoLoaded, loadDemoData, activeInvestigationId, setActiveInvestigation } = useForgeSight()
  const [chainOpen, setChainOpen] = useState(false)
  const [expandedEvidence, setExpandedEvidence] = useState<string | null>(null)
  const [calculationOpen, setCalculationOpen] = useState(false)
  useEffect(() => { void _route }, [_route])
  useEffect(() => { if (data && !activeInvestigationId) setActiveInvestigation(data.investigations[0]?.investigationId ?? null) }, [data, activeInvestigationId, setActiveInvestigation])
  if (!isDemoLoaded || !data) return <InvestigationEmptyState loadDemoData={loadDemoData} />
  const investigation = data.investigations.find((item) => item.investigationId === activeInvestigationId) ?? data.investigations[0]
  if (!investigation) return <InvestigationEmptyState loadDemoData={loadDemoData} />
  const defect = data.defects.find((item) => item.defectType === investigation.defectType)
  const batch = data.batches.find((item) => item.batchId === investigation.batchId)
  const comparisonBatch = data.batches.find((item) => item.batchId !== investigation.batchId && item.line === investigation.line)
  const units = data.units.filter((item) => item.batchId === investigation.batchId && item.line === investigation.line)
  const affectedUnits = units.filter((item) => item.defectType === investigation.defectType)
  const coolingStage = data.productionStages.find((item) => item.stage === batch?.affectedProcessStage)
  const batchObservations = data.processObservations.filter((item) => item.batchId === investigation.batchId && item.line === investigation.line)
  const recommendation = data.recommendations.find((item) => item.id === 'REC-2048-01')
  const economic = calculateEconomicImpact(data.economics, batch, coolingStage)
  const firstOccurrence = affectedUnits.slice().sort((a, b) => a.timestamp.localeCompare(b.timestamp))[0]?.timestamp
  const chain = evidenceOrder.map((id) => data.evidence.find((item) => item.evidenceId === id)).filter((item): item is EvidenceItem => Boolean(item))
  const navigateWithContext = (path: Parameters<typeof navigate>[0], id?: string) => { setActiveInvestigation(investigation.investigationId); navigate(path, id) }
  return <div className="investigation-page">
    <InvestigationHeader investigation={investigation} stage={batch?.affectedProcessStage} onWhy={() => setChainOpen((open) => !open)} chainOpen={chainOpen} />
    {chainOpen && <EvidenceChain items={chain} expandedEvidence={expandedEvidence} onExpand={setExpandedEvidence} onNavigate={(action) => navigateWithContext(action.path, action.id)} />}
    <InvestigationSection number="01" title="What is wrong?" subtitle="Observed product quality signal" icon={ShieldAlert}>
      <div className="investigation-stat-grid"><InvestigationStat label="Affected units" value={String(affectedUnits.length)} status="OBSERVED" /><InvestigationStat label="Surface Crack occurrences" value={String(defect?.occurrenceCount ?? unavailable)} status="OBSERVED" /><InvestigationStat label="Defect rate" value={batch ? `${(batch.defectRate * 100).toFixed(1)}%` : unavailable} status="OBSERVED" /><InvestigationStat label="Temporal trend" value={comparisonBatch && batch ? `Increase: ${comparisonBatch.batchId} to ${batch.batchId}` : unavailable} status="DERIVED" /></div><p className="engineering-note occurrence-note">Occurrence count is distinct from affected unit count.</p>
      <DataFacts facts={[['Defect type', investigation.defectType], ['Affected batch', investigation.batchId], ['Affected line', investigation.line], ['Comparison', comparisonBatch && batch ? `${comparisonBatch.batchId}: ${(comparisonBatch.defectRate * 100).toFixed(1)}% / ${batch.batchId}: ${(batch.defectRate * 100).toFixed(1)}% defect rate` : unavailable]]} />
      <div className="section-actions"><button className="secondary-button" type="button" onClick={() => navigateWithContext('defect-detail', investigation.defectType)}><FileSearch size={15} /> View defect details</button></div>
    </InvestigationSection>
    <InvestigationSection number="02" title="Case snapshot" subtitle="Observed quality and process context from the shared dataset" icon={Network}>
      <div className="investigation-stat-grid"><InvestigationStat label="Process stage" value={batch?.affectedProcessStage ?? unavailable} status="OBSERVED" /><InvestigationStat label="Throughput" value={coolingStage ? `${coolingStage.throughput} units/hr` : unavailable} status="OBSERVED" /><InvestigationStat label="Capacity" value={coolingStage ? `${coolingStage.capacity} units/hr` : unavailable} status="OBSERVED" /><InvestigationStat label="Utilization" value={coolingStage ? `${coolingStage.utilization}%` : unavailable} status="OBSERVED" /><InvestigationStat label="Queue / WIP" value={coolingStage ? String(coolingStage.queueWip) : unavailable} status="OBSERVED" /></div>
      <div className="detail-grid"><DetailField label="Line" value={investigation.line} /><DetailField label="Batch" value={investigation.batchId} /><DetailField label="Defect" value={investigation.defectType} /><DetailField label="Product zone" value={unavailable} /></div>
      <RecordStrip records={affectedUnits.map((unit) => `${unit.unitId} / ${unit.processStage} / ${new Date(unit.timestamp).toLocaleString()}`)} empty="No affected unit records supplied." />
    </InvestigationSection>
    <InvestigationSection number="03" title="Evidence summary" subtitle="Observed, derived, and hypothesis records from the shared evidence chain" icon={FileSearch}>
      <EvidenceSummary items={chain} onNavigate={(action) => navigateWithContext(action.path, action.id)} />
    </InvestigationSection>
    <InvestigationSection number="04" title="When?" subtitle="Chronology of supplied observations" icon={ArrowDown}>
      <div className="investigation-timeline"><TimelineItem label="First affected unit" timestamp={firstOccurrence} detail={`${affectedUnits[0]?.unitId ?? unavailable} recorded as ${investigation.defectType}.`} status="OBSERVED" /><TimelineItem label="Affected batch period" timestamp={batch?.startTime} detail={`${investigation.batchId} ran through ${batch?.endTime ? new Date(batch.endTime).toLocaleString() : unavailable}.`} status="OBSERVED" /><TimelineItem label="Process observation" timestamp={batchObservations.find((item) => item.variable === 'Cycle Time')?.timestamp} detail={batchObservations.find((item) => item.variable === 'Cycle Time') ? `Cooling-stage cycle time was observed at ${batchObservations.find((item) => item.variable === 'Cycle Time')?.value} ${batchObservations.find((item) => item.variable === 'Cycle Time')?.unit}.` : unavailable} status="OBSERVED" /><TimelineItem label="Defect increase" timestamp={batch?.startTime} detail={comparisonBatch && batch ? `${batch.batchId} defect rate is higher than the supplied comparison batch ${comparisonBatch.batchId}.` : unavailable} status="OBSERVED" /></div>
    </InvestigationSection>
    <InvestigationSection number="05" title="Investigation matrix" subtitle="Supplied process observations; no normal range or causal threshold is assumed" icon={BarChart3}>
      <InvestigationMatrix observations={batchObservations} />
      <p className="engineering-note">Observed process values are associated with the affected batch. The supplied data does not establish a normal range or causality.</p>
    </InvestigationSection>
    <InvestigationSection number="06" title="What may be contributing?" subtitle="Potential contributor, not confirmed root cause" icon={FlaskConical}>
      <ContributorPanel recommendation={recommendation} />
    </InvestigationSection>
    <InvestigationSection number="07" title="Production impact" subtitle="Observed stage constraints and throughput exposure" icon={Gauge}>
      <div className="investigation-stat-grid"><InvestigationStat label="Affected stage" value={coolingStage?.stage ?? unavailable} status="OBSERVED" /><InvestigationStat label="Capacity" value={coolingStage ? `${coolingStage.capacity} units/hr` : unavailable} status="OBSERVED" /><InvestigationStat label="Actual throughput" value={coolingStage ? `${coolingStage.throughput} units/hr` : unavailable} status="OBSERVED" /><InvestigationStat label="Capacity gap" value={coolingStage ? `${coolingStage.capacity - coolingStage.throughput} units/hr` : unavailable} status="DERIVED" /><InvestigationStat label="Utilization" value={coolingStage ? `${coolingStage.utilization}%` : unavailable} status="OBSERVED" /><InvestigationStat label="Queue / WIP" value={coolingStage ? String(coolingStage.queueWip) : unavailable} status="OBSERVED" /></div><p className="engineering-note">Throughput exposure is an observed difference between supplied stage capacity and actual throughput; it is not a claim of causality.</p><button className="secondary-button" type="button" onClick={() => navigateWithContext('bottleneck-analysis')}><Network size={15} /> View bottleneck</button>
    </InvestigationSection>
    <InvestigationSection number="08" title="Economic impact" subtitle="Deterministic estimates from supplied assumptions" icon={CircleDollarSign}>
      <div className="economic-grid">{economic.rows.map((row) => <InvestigationStat key={row.label} label={row.label} value={row.displayValue} status={row.status} accent="estimated" />)}</div><p className="engineering-note">Estimated exposure components are shown separately; the supplied assumptions do not establish a non-overlapping additive total.</p><button className="calculation-button" type="button" onClick={() => setCalculationOpen((open) => !open)}><Calculator size={15} /> How calculated? {calculationOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</button>{calculationOpen && <CalculationPanel economic={economic} />}
    </InvestigationSection>
    <InvestigationSection number="09" title="Recommended investigation" subtitle="Shared recommendation record" icon={Target}>
      <div className="recommendation-panel"><div className="recommendation-row"><span>Issue</span><strong>{recommendation?.issue ?? unavailable}</strong></div><div className="recommendation-row"><span>Potential contributor</span><strong>{recommendation?.potentialContributor ?? unavailable}</strong></div><div className="recommendation-row"><span>Affected area</span><strong>{recommendation?.affectedArea ?? unavailable}</strong></div><div className="recommendation-row"><span>Estimated impact</span><strong>{recommendation?.estimatedImpact ?? unavailable}</strong></div><div className="recommendation-row"><span>Recommended investigation</span><strong>{recommendation?.recommendedInvestigation ?? unavailable}</strong></div><div className="recommendation-row"><span>Status</span><strong className="status-text review">{recommendation?.status ?? unavailable}</strong></div></div>
    </InvestigationSection>
    <InvestigationSection number="10" title="Investigation questions" subtitle="Questions supported by the available records" icon={Microscope}>
      <QuestionList questions={['Does the same defect pattern appear in other batches?', 'Do affected batches show similar cooling-stage observations?', 'Is the observed process condition temporally associated with the defect increase?', 'Are unaffected batches available for comparison?', 'Does the supplied data contain enough evidence to test the suspected contributor?']} />
    </InvestigationSection>
    <InvestigationSection number="11" title="Investigation decision state" subtitle="Review state, not causal confirmation" icon={ShieldAlert}>
      <DecisionState />
    </InvestigationSection>
    <InvestigationSection number="12" title="Traceability" subtitle="Identifiers resolved against the shared dataset" icon={FileSearch}>
      <InvestigationTraceability data={data} investigation={investigation} chain={chain} recommendation={recommendation} />
    </InvestigationSection>
    <InvestigationSection number="13" title="Recommended next steps" subtitle="Advisory engineering actions; these do not prove the contributor" icon={ArrowRight}>
      <NextSteps recommendation={recommendation} />
      <div className="investigation-actions"><button className="secondary-button" type="button" onClick={() => navigateWithContext('data-evidence')}><FileSearch size={15} /> Review evidence</button><button className="secondary-button" type="button" onClick={() => navigateWithContext('quality-intelligence')}><ShieldAlert size={15} /> Open Quality Intelligence</button><button className="secondary-button" type="button" onClick={() => navigateWithContext('process-intelligence')}><BarChart3 size={15} /> Open Process Intelligence</button><button className="secondary-button" type="button" onClick={() => navigateWithContext('bottleneck-analysis')}><Network size={15} /> Open Bottleneck Analysis</button><button className="secondary-button" type="button" onClick={() => navigateWithContext('economic-impact')}><CircleDollarSign size={15} /> Open Economic Impact</button><button className="primary-button" type="button" onClick={() => navigateWithContext('decision-center')}><Target size={15} /> Open Decision Center</button></div>
    </InvestigationSection>
    <DataHonesty />
  </div>
}

function InvestigationHeader({ investigation, stage, onWhy, chainOpen }: { investigation: NonNullable<ReturnType<typeof useForgeSight>['data']>['investigations'][number]; stage?: string; onWhy: () => void; chainOpen: boolean }) { return <header className="investigation-header"><div className="case-mark"><Microscope size={22} /></div><div className="case-copy"><span className="eyebrow">Investigation workspace</span><h1>CASE {investigation.investigationId}</h1><strong>{investigation.defectType}</strong><div className="case-tags"><span>{investigation.batchId}</span><span>{investigation.line}</span><span>{stage ?? unavailable}</span><span className="status-text review">{investigation.status}</span><span className="demo-badge">DEMO MODE</span></div><div className="investigation-status-label">INVESTIGATION STATUS</div></div><button className={`why-button ${chainOpen ? 'is-open' : ''}`} type="button" onClick={onWhy}><span>WHY?</span><ArrowDown size={16} /></button></header> }
function InvestigationSection({ number, title, subtitle, icon: Icon, children }: { number: string; title: string; subtitle: string; icon: typeof Gauge; children: ReactNode }) { return <section className="investigation-section"><div className="section-marker"><span>{number}</span><Icon size={17} /></div><div className="section-content"><div className="section-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</div></section> }
function InvestigationStat({ label, value, status, accent }: { label: string; value: string; status: string; accent?: string }) { return <div className={`investigation-stat ${accent ?? ''}`}><span>{label}</span><strong>{value}</strong><small>{status}</small></div> }
function DataFacts({ facts }: { facts: [string, string][] }) { return <div className="facts-grid">{facts.map(([label, value]) => <DetailField key={label} label={label} value={value} />)}</div> }
function DetailField({ label, value }: { label: string; value: string }) { return <div className="detail-field"><span>{label}</span><strong>{value}</strong></div> }
function RecordStrip({ records, empty }: { records: string[]; empty: string }) { return <div className="record-strip">{records.length ? records.map((record) => <span key={record}>{record}</span>) : <span>{empty}</span>}</div> }
function TimelineItem({ label, timestamp, detail, status }: { label: string; timestamp?: string; detail: string; status: string }) { return <div className="timeline-item"><span className="timeline-node" /><div><div className="timeline-meta"><strong>{label}</strong><span>{status} / {timestamp ? new Date(timestamp).toLocaleString() : unavailable}</span></div><p>{detail}</p></div></div> }
function EvidenceChain({ items, expandedEvidence, onExpand, onNavigate }: { items: EvidenceItem[]; expandedEvidence: string | null; onExpand: (id: string | null) => void; onNavigate: (action: { path: Parameters<typeof navigate>[0]; id?: string }) => void }) { return <section className="evidence-chain"><div className="chain-heading"><div><span className="eyebrow">Evidence chain</span><h2>How the case is connected</h2></div><span>Each step is linked to supplied records</span></div><div className="chain-list">{items.map((item, index) => <div className="chain-step" key={item.evidenceId}><button className="chain-toggle" type="button" onClick={() => onExpand(expandedEvidence === item.evidenceId ? null : item.evidenceId)}><span className={`evidence-status ${item.status.toLowerCase()}`}>{item.status}</span><strong>{item.type}</strong>{expandedEvidence === item.evidenceId ? <ChevronDown size={17} /> : <ChevronRight size={17} />}</button>{expandedEvidence === item.evidenceId && <div className="chain-detail"><p>{item.statement}</p><div className="chain-sources">{item.sourceIds.length ? item.sourceIds.map((source) => <code key={source}>{source}</code>) : <span>{unavailable}</span>}</div><span className="chain-explanation">A linked record is evidence of an observed or estimated relationship, not proof of causality.</span>{item.linkedEvidenceIds.length ? <div className="chain-sources">{item.linkedEvidenceIds.map((id) => <button className="inline-link" type="button" key={id} onClick={() => onExpand(id)}>{id}</button>)}</div> : <span className="chain-explanation">Linked evidence: {unavailable}</span>}{evidenceActions[item.evidenceId] && <button className="secondary-button" type="button" onClick={() => onNavigate(evidenceActions[item.evidenceId])}><ExternalLink size={14} /> {evidenceActions[item.evidenceId].label}</button>}</div>}{index < items.length - 1 && <span className="chain-connector"><ArrowDown size={14} /></span>}</div>)}</div></section> }
function EvidenceSummary({ items, onNavigate }: { items: EvidenceItem[]; onNavigate: (action: { path: Parameters<typeof navigate>[0]; id?: string }) => void }) { const groups: Array<[string, EvidenceStatus[]]> = [['OBSERVED', ['OBSERVED']], ['DERIVED / ESTIMATED', ['ESTIMATED', 'SIMULATED']], ['HYPOTHESIS', ['HYPOTHESIS']]]; return <div className="investigation-evidence-groups">{groups.map(([label, statuses]) => <div className={`investigation-evidence-group ${label === 'HYPOTHESIS' ? 'is-hypothesis' : ''}`} key={label}><div className="evidence-group-label"><span>{label}</span><small>{items.filter((item) => statuses.includes(item.status)).length} records</small></div>{items.filter((item) => statuses.includes(item.status)).map((item) => <div className="investigation-evidence-item" key={item.evidenceId}><div className="investigation-evidence-item-heading"><span className={`evidence-status ${item.status.toLowerCase()}`}>{item.status}</span><strong>{item.type}</strong><code>{item.evidenceId}</code></div><p>{item.statement}</p><div className="chain-sources">{item.sourceIds.length ? item.sourceIds.map((source) => <code key={source}>{source}</code>) : <span>{unavailable}</span>}</div><div className="investigation-evidence-links">Linked evidence: {item.linkedEvidenceIds.length ? item.linkedEvidenceIds.map((id) => <code key={id}>{id}</code>) : unavailable}</div>{evidenceActions[item.evidenceId] && <button className="ghost-button" type="button" onClick={() => onNavigate(evidenceActions[item.evidenceId])}><ExternalLink size={13} /> Review in workspace</button>}</div>)}{!items.some((item) => statuses.includes(item.status)) && <p className="muted-cell">{unavailable}</p>}</div>)}</div> }
function InvestigationMatrix({ observations }: { observations: ProcessObservation[] }) { return <div className="investigation-matrix"><table><thead><tr><th>Signal</th><th>Observed value</th><th>Unit</th><th>Batch</th><th>Process stage</th><th>Interpretation</th></tr></thead><tbody>{observations.length ? observations.map((observation) => <tr key={observation.observationId}><td>{observation.variable}</td><td>{observation.value}</td><td>{observation.unit}</td><td>{observation.batchId}</td><td>{observation.processStage}</td><td>Observed process value; requires comparison.</td></tr>) : <tr><td colSpan={6}>{unavailable}</td></tr>}</tbody></table></div> }
function ContributorPanel({ recommendation }: { recommendation?: NonNullable<ReturnType<typeof useForgeSight>['data']>['recommendations'][number] }) { return <div className="contributor-panel"><div className="contributor-heading"><div><span className="eyebrow">POTENTIAL CONTRIBUTOR</span><h3>{recommendation?.potentialContributor ?? unavailable}</h3></div><span className="review-badge">NOT CONFIRMED</span></div><div className="contributor-columns"><div><span className="field-label">Evidence strength</span><p>{recommendation?.evidenceStrength ?? unavailable}</p><span className="field-label">Affected area</span><p>{recommendation?.affectedArea ?? unavailable}</p></div><div><span className="field-label">Estimated impact</span><p>{recommendation?.estimatedImpact ?? unavailable}</p><span className="field-label">Recommendation status</span><p>{recommendation?.status ?? unavailable}</p></div></div><div className="contributor-footer"><p>{recommendation?.recommendedInvestigation ?? unavailable}</p></div></div> }
function QuestionList({ questions }: { questions: string[] }) { return <div className="investigation-question-list">{questions.map((question, index) => <div key={question}><span>{String(index + 1).padStart(2, '0')}</span><p>{question}</p><strong>OPEN QUESTION</strong></div>)}</div> }
function DecisionState() { return <div className="decision-state-panel"><div><span className="field-label">Current conclusion</span><strong>Contributor hypothesis remains unconfirmed.</strong></div><div><span className="field-label">Evidence supports investigation</span><strong className="decision-yes">YES</strong></div><div><span className="field-label">Causal confirmation</span><strong>NOT ESTABLISHED</strong></div></div> }
function InvestigationTraceability({ data, investigation, chain, recommendation }: { data: NonNullable<ReturnType<typeof useForgeSight>['data']>; investigation: NonNullable<ReturnType<typeof useForgeSight>['data']>['investigations'][number]; chain: EvidenceItem[]; recommendation?: NonNullable<ReturnType<typeof useForgeSight>['data']>['recommendations'][number] }) { const defect = data.defects.find((item) => item.defectType === investigation.defectType); const affectedStage = data.batches.find((item) => item.batchId === investigation.batchId)?.affectedProcessStage; const unitIds = data.units.filter((item) => item.batchId === investigation.batchId && item.line === investigation.line).map((item) => item.unitId); const groups: Array<[string, string[]]> = [['Investigation ID', [investigation.investigationId]], ['Batch ID', [investigation.batchId]], ['Defect ID', defect ? [defect.defectId] : []], ['Unit IDs', unitIds], ['Process observation IDs', data.processObservations.filter((item) => item.batchId === investigation.batchId && item.line === investigation.line).map((item) => item.observationId)], ['Production stage IDs', data.productionStages.filter((item) => item.stage === affectedStage).map((item) => item.stageId)], ['Evidence IDs', chain.map((item) => item.evidenceId)], ['Recommendation ID', recommendation ? [recommendation.id] : []], ['Economics ID', data.economics ? [data.economics.economicsId] : []]]; return <div className="investigation-traceability">{groups.map(([label, values]) => <div key={label}><span>{label}</span>{values.length ? values.map((value) => <code key={value}>{value}</code>) : <small>{unavailable}</small>}</div>)}</div> }
function NextSteps({ recommendation }: { recommendation?: NonNullable<ReturnType<typeof useForgeSight>['data']>['recommendations'][number] }) { return <div className="next-step-list"><div><strong>VERIFY</strong><p>{recommendation?.recommendedInvestigation ?? 'Further investigation required.'}</p></div><div><strong>COMPARE</strong><p>Compare affected and unaffected batches if comparison data is available.</p></div><div><strong>TRACE</strong><p>Trace the observed process deviation against the affected batch.</p></div></div> }
function DataHonesty() { return <div className="investigation-honesty"><span className="eyebrow">DATA HONESTY</span><p><strong>OBSERVED</strong> Directly represented in supplied data.</p><p><strong>ESTIMATED</strong> Calculated from supplied inputs.</p><p><strong>SIMULATED</strong> Scenario output.</p><p><strong>HYPOTHESIS</strong> Potential explanation requiring verification.</p></div> }
function CalculationPanel({ economic }: { economic: ReturnType<typeof calculateEconomicImpact> }) { return <div className="calculation-panel"><h3>Deterministic estimate</h3><p>Figures are calculated from shared demo inputs, not generated by an LLM.</p>{economic.formulas.map((formula) => <div className="formula-row" key={formula.label}><span>{formula.label}</span><code>{formula.formula}</code><strong>{formula.value}</strong></div>)}{economic.isPartial && <p className="economic-partial">ECONOMIC DATA PARTIAL / {economic.missingAssumptions.join(', ')}</p>}</div> }
function InvestigationEmptyState({ loadDemoData }: { loadDemoData: () => void }) { return <div className="page-view"><div className="page-heading"><div className="heading-icon"><Microscope size={21} /></div><div><span className="eyebrow">Quality / Investigation</span><h1>Investigation Center</h1></div></div><p className="page-description">Load the centralized ForgeSight demo dataset to open the FS-2048 investigation workspace.</p><button className="primary-button" type="button" onClick={loadDemoData}>Load demo data <ArrowRight size={15} /></button></div> }
