import { useEffect, useState, type ReactNode } from 'react'
import { ArrowDown, ArrowRight, BarChart3, Calculator, ChevronDown, ChevronRight, CircleDollarSign, ExternalLink, FileSearch, FlaskConical, Gauge, Microscope, Network, ShieldAlert, Target } from 'lucide-react'
import { useForgeSight } from '../context/useForgeSight'
import type { EvidenceItem } from '../data/types'
import { calculateEconomicImpact } from '../data/economicCalculations'
import { navigate, type AppRoute } from '../navigation'

const unavailable = 'Not available in supplied data.'
const evidenceOrder = ['EVD-DEFECT-2048', 'EVD-DEVIATION-2048', 'EVD-TEMPORAL-2048', 'EVD-BATCH-2048', 'EVD-CONTRIBUTOR-2048', 'EVD-BOTTLENECK-2048', 'EVD-THROUGHPUT-2048', 'EVD-ECONOMIC-2048', 'EVD-RECOMMENDATION-2048']
const evidenceActions: Record<string, { label: string; path: Parameters<typeof navigate>[0]; id?: string }> = {
  'EVD-DEFECT-2048': { label: 'View defect', path: 'defect-detail', id: 'Surface Crack' },
  'EVD-DEVIATION-2048': { label: 'View process data', path: 'process-intelligence' },
  'EVD-TEMPORAL-2048': { label: 'View records', path: 'quality-intelligence' },
  'EVD-BATCH-2048': { label: 'View batch', path: 'data-evidence' },
  'EVD-CONTRIBUTOR-2048': { label: 'View process data', path: 'process-intelligence' },
  'EVD-BOTTLENECK-2048': { label: 'View bottleneck', path: 'bottleneck-analysis' },
  'EVD-THROUGHPUT-2048': { label: 'View process data', path: 'process-intelligence' },
  'EVD-ECONOMIC-2048': { label: 'View economic impact', path: 'economic-impact' },
  'EVD-RECOMMENDATION-2048': { label: 'Open decision', path: 'decision-center' },
}

export function InvestigationCenterPage({ route: _route }: { route: AppRoute }) {
  const { data, isDemoLoaded, loadDemoData, activeInvestigationId, setActiveInvestigation } = useForgeSight()
  const [chainOpen, setChainOpen] = useState(false)
  const [expandedEvidence, setExpandedEvidence] = useState<string | null>(null)
  const [calculationOpen, setCalculationOpen] = useState(false)
  useEffect(() => { void _route }, [_route])
  useEffect(() => { if (data && !activeInvestigationId) setActiveInvestigation(data.investigations[0]?.investigationId ?? null) }, [data, activeInvestigationId, setActiveInvestigation])
  if (!isDemoLoaded || !data) return <InvestigationEmptyState loadDemoData={loadDemoData} />
  const investigation = data.investigations.find((item) => item.investigationId === activeInvestigationId) ?? data.investigations[0]
  if (!investigation) return <InvestigationEmptyState loadDemoData={loadDemoData} />
  const defect = data.defects.find((item) => item.defectType === investigation.defectType)
  const batch = data.batches.find((item) => item.batchId === investigation.batchId)
  const units = data.units.filter((item) => item.batchId === investigation.batchId && item.line === investigation.line)
  const affectedUnits = units.filter((item) => item.defectType === investigation.defectType)
  const coolingStage = data.productionStages.find((item) => item.stage === batch?.affectedProcessStage)
  const batchObservations = data.processObservations.filter((item) => item.batchId === investigation.batchId && item.line === investigation.line)
  const baselineObservations = data.processObservations.filter((item) => item.batchId !== investigation.batchId && item.line === investigation.line)
  const recommendation = data.recommendations.find((item) => item.id === 'REC-2048-01')
  const economic = calculateEconomicImpact(data.economics, batch, coolingStage)
  const firstOccurrence = affectedUnits.slice().sort((a, b) => a.timestamp.localeCompare(b.timestamp))[0]?.timestamp
  const chain = evidenceOrder.map((id) => data.evidence.find((item) => item.evidenceId === id)).filter((item): item is EvidenceItem => Boolean(item))
  const variableRows = ['Temperature', 'Cycle Time', 'Pressure', 'Utilization', 'Throughput'].map((variable) => {
    const observed = batchObservations.find((item) => item.variable === variable)
    const baseline = baselineObservations.find((item) => item.variable === variable)
    return { variable, observed, baseline }
  }).filter((row) => row.observed)
  const navigateWithContext = (path: Parameters<typeof navigate>[0], id?: string) => { setActiveInvestigation(investigation.investigationId); navigate(path, id) }
  return <div className="investigation-page">
    <InvestigationHeader investigation={investigation} onWhy={() => setChainOpen((open) => !open)} chainOpen={chainOpen} />
    {chainOpen && <EvidenceChain items={chain} expandedEvidence={expandedEvidence} onExpand={setExpandedEvidence} onNavigate={(action) => navigateWithContext(action.path, action.id)} />}
    <InvestigationSection number="01" title="What is wrong?" subtitle="Observed product quality signal" icon={ShieldAlert}>
      <div className="investigation-stat-grid"><InvestigationStat label="Affected units" value={String(affectedUnits.length)} status="OBSERVED" /><InvestigationStat label="Defect occurrence" value={String(defect?.occurrenceCount ?? unavailable)} status="OBSERVED" /><InvestigationStat label="Defect rate" value={batch ? `${(batch.defectRate * 100).toFixed(1)}%` : unavailable} status="OBSERVED" /><InvestigationStat label="Temporal trend" value="Increase in B-2048" status="OBSERVED" /></div>
      <DataFacts facts={[['Defect type', investigation.defectType], ['Affected batch', investigation.batchId], ['Affected line', investigation.line], ['Comparison', 'B-2047: 2.5% / B-2048: 7.5% defect rate']]} />
      <div className="section-actions"><button className="secondary-button" type="button" onClick={() => navigateWithContext('defect-detail', investigation.defectType)}><FileSearch size={15} /> View defect details</button></div>
    </InvestigationSection>
    <InvestigationSection number="02" title="Where?" subtitle="Available location and process context" icon={Network}>
      <div className="detail-grid"><DetailField label="Line" value={investigation.line} /><DetailField label="Batch" value={investigation.batchId} /><DetailField label="Process stage" value={batch?.affectedProcessStage ?? unavailable} /><DetailField label="Product zone" value="Localization unavailable in supplied data." /></div>
      <RecordStrip records={affectedUnits.map((unit) => `${unit.unitId} / ${unit.processStage} / ${new Date(unit.timestamp).toLocaleString()}`)} empty="No affected unit records supplied." />
    </InvestigationSection>
    <InvestigationSection number="03" title="When?" subtitle="Chronology of supplied observations" icon={ArrowDown}>
      <div className="investigation-timeline"><TimelineItem label="First affected unit" timestamp={firstOccurrence} detail={`${affectedUnits[0]?.unitId ?? unavailable} recorded as ${investigation.defectType}.`} status="OBSERVED" /><TimelineItem label="Affected batch period" timestamp={batch?.startTime} detail={`${investigation.batchId} ran through ${batch?.endTime ? new Date(batch.endTime).toLocaleString() : unavailable}.`} status="OBSERVED" /><TimelineItem label="Process observation" timestamp={batchObservations.find((item) => item.variable === 'Cycle Time')?.timestamp} detail="Cooling-stage cycle time was observed at 46 seconds." status="OBSERVED" /><TimelineItem label="Defect increase" timestamp={batch?.startTime} detail="B-2048 defect rate is higher than the supplied comparison batch B-2047." status="OBSERVED" /></div>
    </InvestigationSection>
    <InvestigationSection number="04" title="What changed?" subtitle="Observed process observations, not causal proof" icon={BarChart3}>
      <div className="technical-table"><table><thead><tr><th>Variable</th><th>Baseline</th><th>Observed value</th><th>Deviation</th><th>Period</th><th>Batch</th></tr></thead><tbody>{variableRows.map((row) => <tr key={row.variable}><td>{row.variable}</td><td>{row.baseline ? `${row.baseline.value} ${row.baseline.unit}` : unavailable}</td><td>{row.observed ? `${row.observed.value} ${row.observed.unit}` : unavailable}</td><td>{row.baseline && row.observed ? `${(row.observed.value - row.baseline.value).toFixed(1)} ${row.observed.unit}` : unavailable}</td><td>{row.observed ? new Date(row.observed.timestamp).toLocaleString() : unavailable}</td><td>{row.observed?.batchId ?? unavailable}</td></tr>)}</tbody></table></div><p className="engineering-note">Observed deviation. Evidence suggests an association with the affected batch; requires engineering verification.</p>
    </InvestigationSection>
    <InvestigationSection number="05" title="What may be contributing?" subtitle="Potential contributor, not confirmed root cause" icon={FlaskConical}>
      <div className="contributor-panel"><div className="contributor-heading"><div><span className="eyebrow">Potential contributor</span><h3>Cooling-stage instability</h3></div><span className="review-badge">Requires engineering verification</span></div><div className="contributor-columns"><div><span className="field-label">Supporting observations</span><ul><li>Temperature deviation observed in B-2048</li><li>Cycle-time increase from 38 s to 46 s</li><li>Repeated Surface Crack observations across supplied batches</li><li>Defect-rate increase from B-2047 to B-2048</li></ul></div><div><span className="field-label">Contradictory evidence</span><p>{unavailable}</p><span className="field-label">Affected period</span><p>{batch ? `${new Date(batch.startTime).toLocaleString()} - ${new Date(batch.endTime).toLocaleString()}` : unavailable}</p></div></div><div className="contributor-footer"><span>Evidence strength: <strong>{recommendation?.evidenceStrength ?? unavailable}</strong></span><span>Evidence language: <strong>Observed association</strong></span><p>{recommendation?.recommendedInvestigation ?? unavailable}</p></div></div>
    </InvestigationSection>
    <InvestigationSection number="06" title="Production impact" subtitle="Observed stage constraints and throughput exposure" icon={Gauge}>
      <div className="investigation-stat-grid"><InvestigationStat label="Affected stage" value={coolingStage?.stage ?? unavailable} status="OBSERVED" /><InvestigationStat label="Capacity" value={coolingStage ? `${coolingStage.capacity} units/hr` : unavailable} status="OBSERVED" /><InvestigationStat label="Actual throughput" value={coolingStage ? `${coolingStage.throughput} units/hr` : unavailable} status="OBSERVED" /><InvestigationStat label="Capacity gap" value={coolingStage ? `${coolingStage.capacity - coolingStage.throughput} units/hr` : unavailable} status="OBSERVED" /><InvestigationStat label="Utilization" value={coolingStage ? `${coolingStage.utilization}%` : unavailable} status="OBSERVED" /><InvestigationStat label="Queue / WIP" value={coolingStage ? String(coolingStage.queueWip) : unavailable} status="OBSERVED" /></div><p className="engineering-note">Throughput exposure is an observed difference between supplied stage capacity and actual throughput; it is not a claim of causality.</p><button className="secondary-button" type="button" onClick={() => navigateWithContext('bottleneck-analysis')}><Network size={15} /> View bottleneck</button>
    </InvestigationSection>
    <InvestigationSection number="07" title="Economic impact" subtitle="Deterministic estimates from supplied assumptions" icon={CircleDollarSign}>
      <div className="economic-grid">{economic.rows.map((row) => <InvestigationStat key={row.label} label={row.label} value={row.displayValue} status={row.status} accent="estimated" />)}{economic.total !== null && <InvestigationStat label="Total estimated impact" value={economic.totalDisplay} status="ESTIMATED" accent="estimated" />}</div><button className="calculation-button" type="button" onClick={() => setCalculationOpen((open) => !open)}><Calculator size={15} /> How calculated? {calculationOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</button>{calculationOpen && <CalculationPanel economic={economic} />}
    </InvestigationSection>
    <InvestigationSection number="08" title="Recommended investigation" subtitle="Shared recommendation record" icon={Target}>
      <div className="recommendation-panel"><div className="recommendation-row"><span>Issue</span><strong>{recommendation?.issue ?? unavailable}</strong></div><div className="recommendation-row"><span>Potential contributor</span><strong>{recommendation?.potentialContributor ?? unavailable}</strong></div><div className="recommendation-row"><span>Evidence</span><strong>{recommendation ? 'Temperature deviation / Cycle-time increase / Repeated affected batches / Defect-rate increase' : unavailable}</strong></div><div className="recommendation-row"><span>Recommended investigation</span><strong>{recommendation?.recommendedInvestigation ?? unavailable}</strong></div><div className="recommendation-row"><span>Status</span><strong className="status-text review">{recommendation?.status ?? unavailable}</strong></div></div><button className="primary-button" type="button" onClick={() => navigateWithContext('decision-center')}><Target size={15} /> Open decision</button>
    </InvestigationSection>
  </div>
}

function InvestigationHeader({ investigation, onWhy, chainOpen }: { investigation: NonNullable<ReturnType<typeof useForgeSight>['data']>['investigations'][number]; onWhy: () => void; chainOpen: boolean }) { return <header className="investigation-header"><div className="case-mark"><Microscope size={22} /></div><div className="case-copy"><span className="eyebrow">Investigation workspace</span><h1>CASE {investigation.investigationId}</h1><strong>{investigation.defectType}</strong><div className="case-tags"><span>{investigation.line}</span><span>{investigation.batchId}</span><span className="status-text review">{investigation.status}</span><span className="demo-badge">DEMO MODE</span></div></div><button className={`why-button ${chainOpen ? 'is-open' : ''}`} type="button" onClick={onWhy}><span>WHY?</span><ArrowDown size={16} /></button></header> }
function InvestigationSection({ number, title, subtitle, icon: Icon, children }: { number: string; title: string; subtitle: string; icon: typeof Gauge; children: ReactNode }) { return <section className="investigation-section"><div className="section-marker"><span>{number}</span><Icon size={17} /></div><div className="section-content"><div className="section-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</div></section> }
function InvestigationStat({ label, value, status, accent }: { label: string; value: string; status: string; accent?: string }) { return <div className={`investigation-stat ${accent ?? ''}`}><span>{label}</span><strong>{value}</strong><small>{status}</small></div> }
function DataFacts({ facts }: { facts: [string, string][] }) { return <div className="facts-grid">{facts.map(([label, value]) => <DetailField key={label} label={label} value={value} />)}</div> }
function DetailField({ label, value }: { label: string; value: string }) { return <div className="detail-field"><span>{label}</span><strong>{value}</strong></div> }
function RecordStrip({ records, empty }: { records: string[]; empty: string }) { return <div className="record-strip">{records.length ? records.map((record) => <span key={record}>{record}</span>) : <span>{empty}</span>}</div> }
function TimelineItem({ label, timestamp, detail, status }: { label: string; timestamp?: string; detail: string; status: string }) { return <div className="timeline-item"><span className="timeline-node" /><div><div className="timeline-meta"><strong>{label}</strong><span>{status} / {timestamp ? new Date(timestamp).toLocaleString() : unavailable}</span></div><p>{detail}</p></div></div> }
function EvidenceChain({ items, expandedEvidence, onExpand, onNavigate }: { items: EvidenceItem[]; expandedEvidence: string | null; onExpand: (id: string | null) => void; onNavigate: (action: { path: Parameters<typeof navigate>[0]; id?: string }) => void }) { return <section className="evidence-chain"><div className="chain-heading"><div><span className="eyebrow">Evidence chain</span><h2>How the case is connected</h2></div><span>Each step is linked to supplied records</span></div><div className="chain-list">{items.map((item, index) => <div className="chain-step" key={item.evidenceId}><button className="chain-toggle" type="button" onClick={() => onExpand(expandedEvidence === item.evidenceId ? null : item.evidenceId)}><span className={`evidence-status ${item.status.toLowerCase()}`}>{item.status}</span><strong>{item.type}</strong>{expandedEvidence === item.evidenceId ? <ChevronDown size={17} /> : <ChevronRight size={17} />}</button>{expandedEvidence === item.evidenceId && <div className="chain-detail"><p>{item.statement}</p><div className="chain-sources">{item.sourceIds.map((source) => <code key={source}>{source}</code>)}</div><span className="chain-explanation">Source dataset: ForgeSight Line 03 investigation demo. A linked record is evidence of an observed or estimated relationship, not proof of causality.</span>{evidenceActions[item.evidenceId] && <button className="secondary-button" type="button" onClick={() => onNavigate(evidenceActions[item.evidenceId])}><ExternalLink size={14} /> {evidenceActions[item.evidenceId].label}</button>}</div>}{index < items.length - 1 && <span className="chain-connector"><ArrowDown size={14} /></span>}</div>)}</div></section> }
function CalculationPanel({ economic }: { economic: ReturnType<typeof calculateEconomicImpact> }) { return <div className="calculation-panel"><h3>Deterministic estimate</h3><p>Figures are calculated from shared demo inputs, not generated by an LLM.</p>{economic.formulas.map((formula) => <div className="formula-row" key={formula.label}><span>{formula.label}</span><code>{formula.formula}</code><strong>{formula.value}</strong></div>)}{economic.isPartial && <p className="economic-partial">ECONOMIC DATA PARTIAL / {economic.missingAssumptions.join(', ')}</p>}</div> }
function InvestigationEmptyState({ loadDemoData }: { loadDemoData: () => void }) { return <div className="page-view"><div className="page-heading"><div className="heading-icon"><Microscope size={21} /></div><div><span className="eyebrow">Quality / Investigation</span><h1>Investigation Center</h1></div></div><p className="page-description">Load the centralized ForgeSight demo dataset to open the FS-2048 investigation workspace.</p><button className="primary-button" type="button" onClick={loadDemoData}>Load demo data <ArrowRight size={15} /></button></div> }
