import { ArrowRight, BarChart3, Calculator, CircleDollarSign, ExternalLink, RotateCcw, ShieldAlert, SlidersHorizontal } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useState } from 'react'
import { useForgeSight } from '../context/useForgeSight'
import { calculateProfitabilityScenario, type ProfitabilityResult, type ProfitabilityScenario } from '../data/profitabilityCalculations'
import { navigate, type AppRoute } from '../navigation'

const unavailable = 'Not available in supplied data.'
const money = (value: number | null) => value === null ? unavailable : `${value.toLocaleString(undefined, { maximumFractionDigits: 0 })} demo currency units`
const number = (value: number | null) => value === null ? unavailable : value.toLocaleString(undefined, { maximumFractionDigits: 1 })
const percent = (value: number | null) => value === null ? unavailable : `${(value * 100).toFixed(1)}%`

export function ProfitabilitySimulatorPage({ route }: { route: AppRoute }) {
  const { data, isDemoLoaded, loadDemoData, activeInvestigationId, setActiveInvestigation } = useForgeSight()
  const [showMethodology, setShowMethodology] = useState(false)
  const [selectedPreset, setSelectedPreset] = useState('BASELINE')
  const [scenarioState, setScenarioState] = useState<ProfitabilityScenario | null>(null)
  void route
  if (!isDemoLoaded || !data) return <SimulatorEmptyState loadDemoData={loadDemoData} />

  const investigation = data.investigations.find((item) => item.investigationId === activeInvestigationId) ?? data.investigations[0]
  const batch = data.batches.find((item) => item.batchId === investigation?.batchId)
  const stage = data.productionStages.find((item) => item.stage === batch?.affectedProcessStage)
  if (!investigation || !batch || !stage) return <SimulatorPartialState />
  const cycleObservation = data.processObservations.find((item) => item.processStage === stage?.stage && item.variable === 'Cycle Time' && item.batchId === batch?.batchId)
  const economics = data.economics
  const baseline: ProfitabilityScenario = { defectRate: batch.defectRate, throughput: stage.throughput, cycleTime: cycleObservation?.value ?? null, scrapCost: economics.scrapCost, unitCost: economics.unitCost, sellingPrice: economics.sellingPrice, productionVolume: batch.unitCount, downtimeCost: economics.downtimeCost }
  const scenario = scenarioState ?? baseline
  const result = calculateProfitabilityScenario(scenario, baseline.throughput)
  const baselineResult = calculateProfitabilityScenario(baseline, baseline.throughput)
  const setScenario = (next: ProfitabilityScenario) => setScenarioState(next)
  const setField = <K extends keyof ProfitabilityScenario>(key: K, value: ProfitabilityScenario[K]) => { setScenario({ ...scenario, [key]: value }); setSelectedPreset('CUSTOM') }
  const applyPreset = (preset: string) => {
    setSelectedPreset(preset)
    if (preset === 'BASELINE') setScenario(baseline)
    if (preset === 'DEFECT') setScenario({ ...baseline, defectRate: Math.max(0, baseline.defectRate * .5) })
    if (preset === 'BOTTLENECK') setScenario({ ...baseline, throughput: stage.capacity })
    if (preset === 'CYCLE') setScenario({ ...baseline, cycleTime: baseline.cycleTime === null ? null : baseline.cycleTime * .8 })
    if (preset === 'COMBINED') setScenario({ ...baseline, defectRate: Math.max(0, baseline.defectRate * .5), throughput: stage.capacity, cycleTime: baseline.cycleTime === null ? null : baseline.cycleTime * .8 })
  }
  const go = (path: Parameters<typeof navigate>[0]) => { if (investigation) setActiveInvestigation(investigation.investigationId); navigate(path) }

  return <div className="simulator-page">
    <header className="simulator-header"><div className="economic-heading-icon"><SlidersHorizontal size={22} /></div><div><span className="eyebrow">Economics</span><h1>Profitability Simulator</h1><p>Model how operational improvements could affect throughput, quality, cost, revenue, and estimated profit.</p></div><span className="demo-badge">DEMO MODE</span></header>
    <div className="simulator-context"><span>FS-2048</span><span>B-2048</span><span>LINE 03</span><span>COOLING</span><span>Surface Crack</span></div>
    <div className="simulator-notice"><ShieldAlert size={16} /><strong>SIMULATION</strong><span>ADVISORY ONLY - NO PRODUCTION CONTROL</span></div>

    <section className="simulator-section"><SectionHeading eyebrow="Observed and supplied inputs" title="Baseline" description="The baseline remains anchored to the shared B-2048 investigation." /><div className="simulator-baseline-grid">{[['Defect rate', percent(baseline.defectRate), 'OBSERVED'], ['Throughput', `${number(baseline.throughput)} units/hr`, 'OBSERVED'], ['Capacity', `${number(stage?.capacity ?? null)} units/hr`, 'SUPPLIED'], ['Unit cost', money(baseline.unitCost), 'SUPPLIED'], ['Selling price', money(baseline.sellingPrice), 'SUPPLIED'], ['Scrap cost', money(baseline.scrapCost), 'SUPPLIED'], ['Downtime cost', money(baseline.downtimeCost), 'SUPPLIED']].map(([label, value, status]) => <Metric key={label} label={label} value={value} status={status} />)}</div></section>

    <section className="simulator-section"><SectionHeading eyebrow="Scenario controls" title="Adjust the advisory model" description="Changing a control immediately recalculates the simulated outputs." /><div className="simulator-controls"><Control label="Defect rate" value={scenario.defectRate * 100} min={0} max={30} step={.1} suffix="%" onChange={(value) => setField('defectRate', value / 100)} /><Control label="Throughput" value={scenario.throughput} min={0} max={stage.capacity} step={1} suffix=" units/hr" onChange={(value) => setField('throughput', value)} /><Control label="Cycle time" value={scenario.cycleTime === null ? '' : scenario.cycleTime} min={0} max={120} step={1} suffix=" s" unavailable={scenario.cycleTime === null} onChange={(value) => setField('cycleTime', value)} /><Control label="Scrap cost" value={scenario.scrapCost} min={0} max={200} step={1} onChange={(value) => setField('scrapCost', value)} /><Control label="Unit cost" value={scenario.unitCost} min={0} max={300} step={1} onChange={(value) => setField('unitCost', value)} /><Control label="Selling price" value={scenario.sellingPrice} min={0} max={400} step={1} onChange={(value) => setField('sellingPrice', value)} /><Control label="Production volume" value={scenario.productionVolume === null ? '' : scenario.productionVolume} min={1} max={1000} step={1} suffix=" units" scenarioInput={baseline.productionVolume === null} onChange={(value) => setField('productionVolume', value)} /></div><div className="preset-row"><span className="label">Presets</span>{[['BASELINE', 'Reset baseline'], ['DEFECT', 'Reduce defect rate'], ['BOTTLENECK', 'Improve bottleneck capacity'], ['CYCLE', baseline.cycleTime === null ? 'Cycle-time unavailable' : 'Reduce cycle time'], ['COMBINED', 'Combined improvement']].map(([key, label]) => <button key={key} className={`ghost-button ${selectedPreset === key ? 'is-selected' : ''}`} type="button" disabled={key === 'CYCLE' && baseline.cycleTime === null} onClick={() => applyPreset(key)}>{label}</button>)}</div></section>

    <section className="simulator-section"><div className="simulator-section-heading simulator-heading-row"><SectionHeading eyebrow="Calculated output" title="Baseline vs simulated scenario" description="All values are deterministic estimates from the controls above." /><span className="status-badge status-simulated">SIMULATED / ADVISORY ONLY</span></div><ComparisonTable baseline={baselineResult} scenario={result} baselineScenario={baseline} scenarioInput={scenario} /></section>

    <section className="simulator-grid"><section className="simulator-panel"><SectionHeading eyebrow="Visual summary" title="Scenario signal" description="Purposeful comparison of the current scenario outputs." /><div className="simulator-chart"><ResponsiveContainer width="100%" height={250}><BarChart data={[{ name: 'Throughput', baseline: baseline.throughput, scenario: scenario.throughput }, { name: 'Defect rate %', baseline: baseline.defectRate * 100, scenario: scenario.defectRate * 100 }, { name: 'Revenue / 100', baseline: (baselineResult.revenue ?? 0) / 100, scenario: (result.revenue ?? 0) / 100 }, { name: 'Profit / 100', baseline: (baselineResult.estimatedProfit ?? 0) / 100, scenario: (result.estimatedProfit ?? 0) / 100 }]}><CartesianGrid stroke="#2a383d" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#a9b8b6', fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#71817f', fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: '#131a1d', border: '1px solid #2a383d', color: '#edf3f1' }} /><Bar dataKey="baseline" name="Baseline" fill="#71817f" radius={[2, 2, 0, 0]} /><Bar dataKey="scenario" name="Simulated" fill="#63b8d2" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="simulator-summary-grid">{[['Throughput', `${number(scenario.throughput)} units/hr`], ['Defect rate', percent(scenario.defectRate)], ['Estimated revenue', money(result.revenue)], ['Estimated profit', money(result.estimatedProfit)], ['Estimated margin', percent(result.estimatedMargin)]].map(([label, value]) => <Metric key={label} label={label} value={value} status="SIMULATED" />)}</div></section><section className="simulator-panel"><SectionHeading eyebrow="Scenario comparison" title="Compare with baseline" description="Neutral comparison of modeled changes." /><ComparisonSignals baseline={baselineResult} scenario={result} baselineScenario={baseline} scenarioInput={scenario} /></section></section>

    <section className="simulator-panel assumptions-panel"><SectionHeading eyebrow="Traceability" title="Assumptions & evidence" description="Observed context and supplied economics remain visible beside the model." /><div className="assumption-columns"><div><h3>Observed context</h3><p>B-2048 / LINE 03 / COOLING / Surface Crack</p><p>{percent(baseline.defectRate)} observed defect rate</p><p>{number(baseline.throughput)} units/hr observed throughput</p></div><div><h3>Supplied economic assumptions</h3><p>Unit cost = {economics.unitCost}</p><p>Selling price = {economics.sellingPrice}</p><p>Scrap cost = {economics.scrapCost}</p><p>Downtime cost = {economics.downtimeCost.toLocaleString()}</p><p>Revenue exposure = {economics.revenueExposure.toLocaleString()}</p></div></div><p className="engineering-note">Simulation outputs are scenario estimates derived from supplied assumptions. They are not observed production results.</p><button className="ghost-button" type="button" onClick={() => go('economic-impact')}><CircleDollarSign size={15} /> View Economic Impact context <ExternalLink size={14} /></button></section>

    <section className="simulator-panel methodology-panel"><div className="simulator-heading-row"><SectionHeading eyebrow="Method" title="Calculation methodology" description="Inspect the deterministic formulas and data honesty boundaries." /><button className="calculation-button" type="button" onClick={() => setShowMethodology((open) => !open)}><Calculator size={15} /> {showMethodology ? 'Hide calculations' : 'How calculated?'}</button></div>{showMethodology && <div className="methodology-list"><MethodRow label="Defective units" formula="production volume x defect rate" value={number(result.defectiveUnits)} /><MethodRow label="Good units" formula="production volume - defective units" value={number(result.goodUnits)} /><MethodRow label="Revenue" formula="good units x selling price" value={money(result.revenue)} /><MethodRow label="Material cost" formula="production volume x unit cost" value={money(result.materialCost)} /><MethodRow label="Estimated profit" formula="revenue - material cost - scrap cost impact - downtime cost" value={money(result.estimatedProfit)} /><MethodRow label="Estimated margin" formula="estimated profit / revenue" value={percent(result.estimatedMargin)} /><MethodRow label="Cycle time relationship" formula="No supplied formula converts cycle time into throughput" value={unavailable} /></div>}</section>

    <footer className="economic-actions"><button className="secondary-button" type="button" onClick={() => go('economic-impact')}><CircleDollarSign size={15} /> View Economic Impact</button><button className="ghost-button" type="button" onClick={() => go('bottleneck-analysis')}><BarChart3 size={15} /> View Bottleneck</button><button className="ghost-button" type="button" onClick={() => go('investigation-center')}><ArrowRight size={15} /> View Investigation</button><button className="ghost-button" type="button" onClick={() => applyPreset('BASELINE')}><RotateCcw size={15} /> Reset Scenario</button></footer>
  </div>
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="economic-section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div> }
function Metric({ label, value, status }: { label: string; value: string; status: string }) { return <article className="simulator-metric"><span className="label">{label}</span><strong>{value}</strong><span className={`status-badge ${status === 'OBSERVED' ? 'status-observed' : status === 'SUPPLIED' ? 'status-estimated' : 'status-simulated'}`}>{status}</span></article> }
function Control({ label, value, min, max, step, suffix = '', unavailable: isUnavailable = false, scenarioInput = false, onChange }: { label: string; value: number | string; min: number; max: number; step: number; suffix?: string; unavailable?: boolean; scenarioInput?: boolean; onChange: (value: number) => void }) { const display = isUnavailable ? unavailable : `${value}${suffix}`; return <label className="simulator-control"><span className="label">{label}</span><div className="control-value"><input type="number" value={isUnavailable ? '' : value} min={min} max={max} step={step} disabled={isUnavailable} onChange={(event) => onChange(Number(event.target.value))} /><span>{display}</span></div>{!isUnavailable && <input type="range" value={Number(value)} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))} />}{scenarioInput && <small>SCENARIO INPUT</small>}</label> }
function ComparisonTable({ baseline, scenario, baselineScenario, scenarioInput }: { baseline: ProfitabilityResult; scenario: ProfitabilityResult; baselineScenario: ProfitabilityScenario; scenarioInput: ProfitabilityScenario }) { const rows: Array<[string, string, string, string]> = [['Defect rate', percent(baselineScenario.defectRate), percent(scenarioInput.defectRate), percent(scenarioInput.defectRate - baselineScenario.defectRate)], ['Good units', number(baseline.goodUnits), number(scenario.goodUnits), number(delta(scenario.goodUnits, baseline.goodUnits))], ['Defective units', number(baseline.defectiveUnits), number(scenario.defectiveUnits), number(delta(scenario.defectiveUnits, baseline.defectiveUnits))], ['Throughput', `${number(baselineScenario.throughput)} units/hr`, `${number(scenarioInput.throughput)} units/hr`, `${number(scenario.throughputDelta)} units/hr`], ['Revenue', money(baseline.revenue), money(scenario.revenue), money(delta(scenario.revenue, baseline.revenue))], ['Material cost', money(baseline.materialCost), money(scenario.materialCost), money(delta(scenario.materialCost, baseline.materialCost))], ['Scrap cost', money(baseline.scrapCostImpact), money(scenario.scrapCostImpact), money(delta(scenario.scrapCostImpact, baseline.scrapCostImpact))], ['Estimated profit', money(baseline.estimatedProfit), money(scenario.estimatedProfit), money(delta(scenario.estimatedProfit, baseline.estimatedProfit))], ['Estimated margin', percent(baseline.estimatedMargin), percent(scenario.estimatedMargin), percent(delta(scenario.estimatedMargin, baseline.estimatedMargin))]]; return <div className="simulator-table-wrap"><table><thead><tr><th>Metric</th><th>Baseline</th><th>Simulated scenario</th><th>Delta</th></tr></thead><tbody>{rows.map(([label, base, simulated, change]) => <tr key={label}><td>{label}</td><td>{base}</td><td>{simulated}</td><td className="simulator-delta">{change}</td></tr>)}</tbody></table></div> }
function ComparisonSignals({ baseline, scenario, baselineScenario, scenarioInput }: { baseline: ProfitabilityResult; scenario: ProfitabilityResult; baselineScenario: ProfitabilityScenario; scenarioInput: ProfitabilityScenario }) { const items = [['Quality', `${percent(baselineScenario.defectRate)} -> ${percent(scenarioInput.defectRate)}`], ['Throughput', `${number(baselineScenario.throughput)} -> ${number(scenarioInput.throughput)} units/hr`], ['Revenue', money(delta(scenario.revenue, baseline.revenue))], ['Cost', money(delta(scenario.estimatedTotalCost, baseline.estimatedTotalCost))], ['Profitability', money(delta(scenario.estimatedProfit, baseline.estimatedProfit))]]; return <div className="signal-list">{items.map(([label, value]) => <div key={label}><span className="label">{label}</span><strong>{value}</strong><small>SIMULATED DELTA</small></div>)}</div> }
function MethodRow({ label, formula, value }: { label: string; formula: string; value: string }) { return <div className="methodology-row"><span className="status-badge status-simulated">SIMULATED OUTPUT</span><div><strong>{label}</strong><code>{formula}</code><small>{value}</small></div></div> }
function delta(value: number | null, baseline: number | null) { return value === null || baseline === null ? null : value - baseline }
function SimulatorEmptyState({ loadDemoData }: { loadDemoData: () => void }) { return <div className="page-view"><div className="page-heading"><div className="heading-icon"><SlidersHorizontal size={21} /></div><div><span className="eyebrow">Economics</span><h1>Profitability Simulator</h1></div></div><p className="page-description">Load the centralized ForgeSight demo dataset to model the FS-2048 investigation.</p><button className="primary-button" type="button" onClick={loadDemoData}>Load demo data <ArrowRight size={15} /></button></div> }
function SimulatorPartialState() { return <div className="page-view"><div className="page-heading"><div className="heading-icon"><SlidersHorizontal size={21} /></div><div><span className="eyebrow">Economics</span><h1>Profitability Simulator</h1></div></div><p className="page-description">ECONOMIC DATA PARTIAL</p><p className="engineering-note">Not available in supplied data. A valid investigation, batch, and production stage are required before simulation outputs can be calculated.</p></div> }