import { Activity, ArrowRight, CircleAlert, CircleDollarSign, FileSearch, Network, Target, Workflow } from 'lucide-react'
import { useState } from 'react'
import type { DemoDataset, ProcessObservation } from '../../data/types'
import { navigate } from '../../navigation'

const unavailable = 'Not available in supplied data.'
const noBaseline = 'No comparison baseline available in supplied data.'
const variables = ['Temperature', 'Cycle Time', 'Pressure', 'Utilization', 'Throughput'] as const
type ProcessVariable = typeof variables[number]
type EvidenceFilter = 'All' | ProcessVariable

export function ProcessIntelligenceWorkspace({ data }: { data: DemoDataset }) {
  const [selectedObservationId, setSelectedObservationId] = useState('OBS-2048-TEMP')
  const [activeFilter, setActiveFilter] = useState<EvidenceFilter>('All')
  const [search, setSearch] = useState('')
  const investigation = data.investigations.find((item) => item.investigationId === 'FS-2048') ?? data.investigations[0]
  const batch = data.batches.find((item) => item.batchId === investigation?.batchId) ?? data.batches.find((item) => item.batchId === 'B-2048')
  const observations = data.processObservations.filter((item) => item.batchId === batch?.batchId && item.line === investigation?.line)
  const selectedObservation = observations.find((item) => item.observationId === selectedObservationId) ?? observations[0]
  const cooling = data.productionStages.find((item) => item.stage === batch?.affectedProcessStage)
  const comparisonObservations = data.processObservations.filter((item) => item.batchId !== batch?.batchId && item.line === investigation?.line)
  const query = search.trim().toLowerCase()
  const filteredObservations = data.processObservations.filter((item) => {
    const matchesVariable = activeFilter === 'All' || item.variable === activeFilter
    const searchable = [item.observationId, item.processStage, item.variable, item.value, item.unit, item.batchId, item.line, item.timestamp].join(' ').toLowerCase()
    return matchesVariable && (!query || searchable.includes(query))
  })
  const evidence = selectedObservation ? data.evidence.filter((item) => item.sourceIds.includes(selectedObservation.observationId) || item.linkedEvidenceIds.some((id) => data.evidence.find((candidate) => candidate.evidenceId === id)?.sourceIds.includes(selectedObservation.observationId))) : []
  const stageId = cooling?.stageId
  const recommendation = data.recommendations.find((item) => item.evidence.some((id) => evidence.some((record) => record.evidenceId === id))) ?? data.recommendations[0]
  const go = (path: Parameters<typeof navigate>[0]) => navigate(path)

  return <div className="process-intelligence-workspace">
    <header className="process-case-header"><div className="process-case-icon"><Activity size={22} /></div><div><span className="eyebrow">PROCESS INTELLIGENCE</span><h1>{batch?.batchId ?? 'BATCH NOT AVAILABLE'} / {investigation?.line ?? 'LINE NOT AVAILABLE'}</h1><p>{investigation?.defectType ?? unavailable} investigation at {batch?.affectedProcessStage ?? unavailable}</p><div className="process-case-tags"><span>{investigation?.investigationId ?? unavailable}</span><span>{batch?.batchId ?? unavailable}</span><span>{investigation?.line ?? unavailable}</span><span>{batch?.affectedProcessStage ?? unavailable}</span><span className="status-text review">{investigation?.status ?? unavailable}</span></div></div><span className="demo-badge">DEMO MODE</span></header>
    <div className="process-advisory"><CircleAlert size={15} /><strong>PROCESS CONTEXT - ADVISORY ANALYSIS</strong><span>Observed conditions are associated with the affected batch; the supplied data does not establish causality.</span></div>
    <div className="process-workspace-actions"><button className="secondary-button" type="button" onClick={() => go('investigation-center')}><FileSearch size={15} /> Investigation Center</button><button className="secondary-button" type="button" onClick={() => go('bottleneck-analysis')}><Network size={15} /> Bottleneck Analysis</button></div>

    <section className="process-intel-panel"><PanelHeading eyebrow="Batch-specific process view" title="What was observed during B-2048?" description="Only supplied observations for the affected batch and line are shown in this view." /><div className="process-observation-table"><table><thead><tr><th>Observation ID</th><th>Process stage</th><th>Variable</th><th>Value</th><th>Timestamp</th><th>Batch</th><th>Line</th></tr></thead><tbody>{observations.length ? observations.map((item) => <tr key={item.observationId} className={selectedObservation?.observationId === item.observationId ? 'selected-row' : ''} onClick={() => setSelectedObservationId(item.observationId)}><td><code>{item.observationId}</code></td><td>{item.processStage}</td><td>{item.variable}</td><td>{item.value} {item.unit}</td><td>{formatTimestamp(item.timestamp)}</td><td>{item.batchId}</td><td>{item.line}</td></tr>) : <tr><td colSpan={7}>{unavailable}</td></tr>}</tbody></table></div></section>

    <section className="process-intel-panel"><PanelHeading eyebrow="Process signal cards" title="Signals available for engineering review" description="No normal ranges are inferred. Comparison values appear only where supplied records exist." /><div className="process-signal-grid">{variables.map((variable) => <SignalCard key={variable} variable={variable} observations={observations} comparison={comparisonObservations.filter((item) => item.variable === variable)} onSelect={setSelectedObservationId} />)}</div></section>

    <section className="process-intel-panel"><PanelHeading eyebrow="Temporal association - not causal proof" title="What was happening during this batch?" description="Chronological placement of supplied B-2048 process observations." /><div className="process-temporal-list">{observations.slice().sort((left, right) => left.timestamp.localeCompare(right.timestamp)).map((item) => <button type="button" key={item.observationId} className={selectedObservation?.observationId === item.observationId ? 'is-selected' : ''} onClick={() => setSelectedObservationId(item.observationId)}><span>{formatTimestamp(item.timestamp)}</span><strong>{item.variable}</strong><b>{item.value} {item.unit}</b><code>{item.observationId}</code></button>)}</div></section>

    <section className="process-intel-panel"><PanelHeading eyebrow="Process deviation evidence" title="Observed process evidence connected to the investigation" description="Existing evidence links are shown without adding causal interpretation." /><div className="process-evidence-connection"><div><span className="label">Observed process evidence</span><strong>{selectedObservation ? `${selectedObservation.variable}: ${selectedObservation.value} ${selectedObservation.unit}` : unavailable}</strong><small>{selectedObservation?.observationId ?? unavailable}</small></div><ArrowRight size={17} /><div><span className="label">Associated evidence</span>{evidence.length ? evidence.map((item) => <code key={item.evidenceId}>{item.evidenceId} / {item.status}</code>) : <strong>{unavailable}</strong>}</div><ArrowRight size={17} /><div><span className="label">Investigation context</span><strong>{investigation ? `${investigation.investigationId} / ${investigation.defectType}` : unavailable}</strong></div></div></section>

    <section className="process-intel-two-column"><section className="process-intel-panel"><PanelHeading eyebrow="Affected vs other data" title="Comparison availability" description="Comparison records are shown only when they share the supplied line and variable." /><div className="comparison-status"><span className="label">Affected batch</span><strong>{batch?.batchId ?? unavailable}</strong><span className="label">Comparison data</span><strong>{comparisonObservations.length ? 'AVAILABLE' : 'NOT AVAILABLE'}</strong></div>{comparisonObservations.length ? <div className="comparison-list">{comparisonObservations.map((item) => <div key={item.observationId}><span>{item.variable}</span><strong>{item.value} {item.unit}</strong><code>{item.batchId} / {item.observationId}</code></div>)}</div> : <p className="engineering-note">Insufficient comparison data in supplied dataset.</p>}</section><section className="process-intel-panel"><PanelHeading eyebrow="Bottleneck connection" title={cooling?.stage ?? 'Affected stage'} description="Production-stage values supplied for the relevant process stage." /><div className="bottleneck-context-grid"><Metric label="Capacity" value={cooling ? `${cooling.capacity} units/hr` : unavailable} status="OBSERVED / SUPPLIED" /><Metric label="Throughput" value={cooling ? `${cooling.throughput} units/hr` : unavailable} status="OBSERVED / SUPPLIED" /><Metric label="Utilization" value={cooling ? `${cooling.utilization}%` : unavailable} status="OBSERVED / SUPPLIED" /><Metric label="Queue / WIP" value={cooling ? String(cooling.queueWip) : unavailable} status="OBSERVED / SUPPLIED" /><Metric label="Throughput gap" value={cooling ? `${cooling.capacity - cooling.throughput} units/hr` : unavailable} status="DERIVED" /></div><button className="secondary-button" type="button" onClick={() => go('bottleneck-analysis')}><Network size={15} /> Open Bottleneck Analysis</button></section></section>

    <section className="process-intel-panel"><div className="process-investigation-heading"><PanelHeading eyebrow="Why this matters to the investigation" title="From observed condition to engineering action" description="The chain distinguishes supplied records, association, and hypothesis." /><span className="hypothesis-flag">HYPOTHESIS / NOT CONFIRMED</span></div><div className="investigation-relevance"><Relevance label="Observed" text="Process observations exist for the affected batch." /><Relevance label="Associated" text={evidence.length ? `Existing evidence links ${selectedObservation?.observationId ?? 'the observation'} with the investigation.` : unavailable} /><Relevance label="Hypothesis" text="Cooling-stage instability is a potential contributor." /><Relevance label="Not established" text="The supplied data does not prove causality." /><Relevance label="Engineering action" text={recommendation?.recommendedInvestigation ?? 'Further investigation required.'} /></div><button className="primary-button" type="button" onClick={() => go('investigation-center')}><Target size={15} /> Review Investigation Center</button></section>

    <section className="process-intel-panel"><div className="process-table-heading"><PanelHeading eyebrow="Process evidence table" title="Search and filter supplied observations" description="Select a record to update the traceability panel." /><label className="process-search"><FileSearch size={14} /><span className="sr-only">Search observations</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search observations" /></label></div><div className="process-filter-row">{(['All', ...variables] as EvidenceFilter[]).map((filter) => <button type="button" key={filter} className={activeFilter === filter ? 'is-selected' : ''} onClick={() => setActiveFilter(filter)}>{filter}</button>)}</div><div className="process-observation-table"><table><thead><tr><th>Observation ID</th><th>Variable</th><th>Value</th><th>Stage</th><th>Batch</th><th>Line</th><th>Timestamp</th></tr></thead><tbody>{filteredObservations.length ? filteredObservations.map((item) => <tr key={item.observationId} className={selectedObservation?.observationId === item.observationId ? 'selected-row' : ''} onClick={() => setSelectedObservationId(item.observationId)}><td><code>{item.observationId}</code></td><td>{item.variable}</td><td>{item.value} {item.unit}</td><td>{item.processStage}</td><td>{item.batchId}</td><td>{item.line}</td><td>{formatTimestamp(item.timestamp)}</td></tr>) : <tr><td colSpan={7}>No matching observations.</td></tr>}</tbody></table></div></section>

    {selectedObservation && <ObservationTraceability observation={selectedObservation} data={data} evidence={evidence} stageId={stageId} />}
    <footer className="process-intelligence-actions"><button className="secondary-button" type="button" onClick={() => go('production-flow')}><Workflow size={15} /> Production Flow</button><button className="secondary-button" type="button" onClick={() => go('economic-impact')}><CircleDollarSign size={15} /> Economic Impact</button><button className="secondary-button" type="button" onClick={() => go('data-evidence')}><FileSearch size={15} /> Data &amp; Evidence</button><button className="primary-button" type="button" onClick={() => go('decision-center')}><Target size={15} /> Decision Center</button></footer>
    <div className="process-data-honesty"><span className="eyebrow">DATA HONESTY</span><span><b>OBSERVED</b> Directly represented in supplied data.</span><span><b>DERIVED</b> Calculated from supplied values.</span><span><b>ESTIMATED</b> Calculated using supplied economic assumptions.</span><span><b>SIMULATED</b> Scenario output from the profitability simulator.</span><span><b>HYPOTHESIS</b> Potential explanation requiring engineering verification.</span></div>
  </div>
}

function PanelHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="process-intel-panel-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div> }
function SignalCard({ variable, observations, comparison, onSelect }: { variable: ProcessVariable; observations: ProcessObservation[]; comparison: ProcessObservation[]; onSelect: (id: string) => void }) { const selected = observations[0]; return <button type="button" className="process-signal-card" onClick={() => selected && onSelect(selected.observationId)}><span className="label">{variable}</span><strong>{selected ? `${selected.value} ${selected.unit}` : unavailable}</strong><small>{selected ? `${formatTimestamp(selected.timestamp)} / ${selected.observationId}` : unavailable}</small><em>{comparison.length ? `${comparison.length} comparison record${comparison.length === 1 ? '' : 's'} available` : noBaseline}</em></button> }
function Metric({ label, value, status }: { label: string; value: string; status: string }) { return <div><span className="label">{label}</span><strong>{value}</strong><small>{status}</small></div> }
function Relevance({ label, text }: { label: string; text: string }) { return <div><span>{label}</span><p>{text}</p></div> }
function ObservationTraceability({ observation, data, evidence, stageId }: { observation: ProcessObservation; data: DemoDataset; evidence: DemoDataset['evidence']; stageId?: string }) { const investigation = data.investigations.find((item) => item.batchId === observation.batchId && item.line === observation.line); return <section className="process-traceability"><div className="process-traceability-heading"><div><span className="eyebrow">Selected observation traceability</span><h2>{observation.observationId}</h2></div><span className="observed-tag">OBSERVED</span></div><div className="process-traceability-grid"><TraceItem label="Observation ID" values={[observation.observationId]} /><TraceItem label="Batch / Line" values={[observation.batchId, observation.line]} /><TraceItem label="Timestamp" values={[formatTimestamp(observation.timestamp)]} /><TraceItem label="Evidence IDs" values={evidence.length ? evidence.map((item) => item.evidenceId) : []} /><TraceItem label="Investigation ID" values={investigation ? [investigation.investigationId] : []} /><TraceItem label="Production stage ID" values={stageId ? [stageId] : []} /></div></section> }
function TraceItem({ label, values }: { label: string; values: string[] }) { return <div><span className="label">{label}</span>{values.length ? values.map((value) => <code key={value}>{value}</code>) : <small>{unavailable}</small>}</div> }
function formatTimestamp(value: string) { return new Date(value).toLocaleString() }
